/*
 * API Gateway Pagamenti
 * Set API REST PagoPA
 *
 * OpenAPI spec version: 1.0
 * Contact: pagamenti.produzione@maggioli.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DebitoDto;
import io.swagger.client.model.NumeroAvvisoDto;
import java.io.IOException;

/**
 * AvvisoPagamentoDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-23T07:57:29.055Z")
public class AvvisoPagamentoDto {
  @SerializedName("debitoDto")
  private DebitoDto debitoDto = null;

  @SerializedName("numeroAvvisoDto")
  private NumeroAvvisoDto numeroAvvisoDto = null;

  public AvvisoPagamentoDto debitoDto(DebitoDto debitoDto) {
    this.debitoDto = debitoDto;
    return this;
  }

   /**
   * Get debitoDto
   * @return debitoDto
  **/
  @ApiModelProperty(value = "")
  public DebitoDto getDebitoDto() {
    return debitoDto;
  }

  public void setDebitoDto(DebitoDto debitoDto) {
    this.debitoDto = debitoDto;
  }

  public AvvisoPagamentoDto numeroAvvisoDto(NumeroAvvisoDto numeroAvvisoDto) {
    this.numeroAvvisoDto = numeroAvvisoDto;
    return this;
  }

   /**
   * Get numeroAvvisoDto
   * @return numeroAvvisoDto
  **/
  @ApiModelProperty(value = "")
  public NumeroAvvisoDto getNumeroAvvisoDto() {
    return numeroAvvisoDto;
  }

  public void setNumeroAvvisoDto(NumeroAvvisoDto numeroAvvisoDto) {
    this.numeroAvvisoDto = numeroAvvisoDto;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AvvisoPagamentoDto avvisoPagamentoDto = (AvvisoPagamentoDto) o;
    return Objects.equals(this.debitoDto, avvisoPagamentoDto.debitoDto) &&
        Objects.equals(this.numeroAvvisoDto, avvisoPagamentoDto.numeroAvvisoDto);
  }

  @Override
  public int hashCode() {
    return Objects.hash(debitoDto, numeroAvvisoDto);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AvvisoPagamentoDto {\n");
    
    sb.append("    debitoDto: ").append(toIndentedString(debitoDto)).append("\n");
    sb.append("    numeroAvvisoDto: ").append(toIndentedString(numeroAvvisoDto)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

