/*
 * API Gateway Pagamenti
 * Set API REST PagoPA
 *
 * OpenAPI spec version: 1.0
 * Contact: pagamenti.produzione@maggioli.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Callback di notifica transazione pagamento. Tali URL verranno invocati al termine dell&#39;intero ciclo di pagamento. Nello specifico dopo che il FESP notificherà a PagoPA (con un OK o un KO) l&#39;esito della transazione di pagamento, PagoPA notificherà a sua volta tale esito
 */
@ApiModel(description = "Callback di notifica transazione pagamento. Tali URL verranno invocati al termine dell'intero ciclo di pagamento. Nello specifico dopo che il FESP notificherà a PagoPA (con un OK o un KO) l'esito della transazione di pagamento, PagoPA notificherà a sua volta tale esito")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-23T07:57:29.055Z")
public class BackUrlDto {
  @SerializedName("backUrlKO")
  private String backUrlKO = null;

  @SerializedName("backUrlNotify")
  private String backUrlNotify = null;

  @SerializedName("backUrlOK")
  private String backUrlOK = null;

  public BackUrlDto backUrlKO(String backUrlKO) {
    this.backUrlKO = backUrlKO;
    return this;
  }

   /**
   * Get backUrlKO
   * @return backUrlKO
  **/
  @ApiModelProperty(example = "urlPageKO", required = true, value = "")
  public String getBackUrlKO() {
    return backUrlKO;
  }

  public void setBackUrlKO(String backUrlKO) {
    this.backUrlKO = backUrlKO;
  }

  public BackUrlDto backUrlNotify(String backUrlNotify) {
    this.backUrlNotify = backUrlNotify;
    return this;
  }

   /**
   * Callback di notifica pagamento contabilizzato. L’URL verrà usato dal batch dedicato per notificare il pagamento in maniera asincrona appena i dati del pagamento saranno disponibili a JPPA
   * @return backUrlNotify
  **/
  @ApiModelProperty(example = "https://httpstat.us/200", value = "Callback di notifica pagamento contabilizzato. L’URL verrà usato dal batch dedicato per notificare il pagamento in maniera asincrona appena i dati del pagamento saranno disponibili a JPPA")
  public String getBackUrlNotify() {
    return backUrlNotify;
  }

  public void setBackUrlNotify(String backUrlNotify) {
    this.backUrlNotify = backUrlNotify;
  }

  public BackUrlDto backUrlOK(String backUrlOK) {
    this.backUrlOK = backUrlOK;
    return this;
  }

   /**
   * Get backUrlOK
   * @return backUrlOK
  **/
  @ApiModelProperty(example = "urlPageOK", required = true, value = "")
  public String getBackUrlOK() {
    return backUrlOK;
  }

  public void setBackUrlOK(String backUrlOK) {
    this.backUrlOK = backUrlOK;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BackUrlDto backUrlDto = (BackUrlDto) o;
    return Objects.equals(this.backUrlKO, backUrlDto.backUrlKO) &&
        Objects.equals(this.backUrlNotify, backUrlDto.backUrlNotify) &&
        Objects.equals(this.backUrlOK, backUrlDto.backUrlOK);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backUrlKO, backUrlNotify, backUrlOK);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BackUrlDto {\n");
    
    sb.append("    backUrlKO: ").append(toIndentedString(backUrlKO)).append("\n");
    sb.append("    backUrlNotify: ").append(toIndentedString(backUrlNotify)).append("\n");
    sb.append("    backUrlOK: ").append(toIndentedString(backUrlOK)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

