/*
 * API Gateway Pagamenti
 * Set API REST PagoPA
 *
 * OpenAPI spec version: 1.0
 * Contact: pagamenti.produzione@maggioli.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ContribuenteDebitoDto;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * Tipo complesso che racchiude i criteri di ricerca utilizzabili da questo servizio
 */
@ApiModel(description = "Tipo complesso che racchiude i criteri di ricerca utilizzabili da questo servizio")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-23T07:57:29.055Z")
public class CriteriRicercaDto {
  @SerializedName("adataFineValidita")
  private OffsetDateTime adataFineValidita = null;

  @SerializedName("adataInizioValidita")
  private OffsetDateTime adataInizioValidita = null;

  @SerializedName("adataInserimento")
  private OffsetDateTime adataInserimento = null;

  @SerializedName("adataLimitePagabilita")
  private OffsetDateTime adataLimitePagabilita = null;

  @SerializedName("codiceIpa")
  private String codiceIpa = null;

  @SerializedName("codiceTipoDebito")
  private String codiceTipoDebito = null;

  @SerializedName("contribuente")
  private ContribuenteDebitoDto contribuente = null;

  @SerializedName("daDataFineValidita")
  private OffsetDateTime daDataFineValidita = null;

  @SerializedName("daDataInizioValidita")
  private OffsetDateTime daDataInizioValidita = null;

  @SerializedName("daDataInserimento")
  private OffsetDateTime daDataInserimento = null;

  @SerializedName("daDataLimitePagabilita")
  private OffsetDateTime daDataLimitePagabilita = null;

  public CriteriRicercaDto adataFineValidita(OffsetDateTime adataFineValidita) {
    this.adataFineValidita = adataFineValidita;
    return this;
  }

   /**
   * Get adataFineValidita
   * @return adataFineValidita
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getAdataFineValidita() {
    return adataFineValidita;
  }

  public void setAdataFineValidita(OffsetDateTime adataFineValidita) {
    this.adataFineValidita = adataFineValidita;
  }

  public CriteriRicercaDto adataInizioValidita(OffsetDateTime adataInizioValidita) {
    this.adataInizioValidita = adataInizioValidita;
    return this;
  }

   /**
   * Get adataInizioValidita
   * @return adataInizioValidita
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getAdataInizioValidita() {
    return adataInizioValidita;
  }

  public void setAdataInizioValidita(OffsetDateTime adataInizioValidita) {
    this.adataInizioValidita = adataInizioValidita;
  }

  public CriteriRicercaDto adataInserimento(OffsetDateTime adataInserimento) {
    this.adataInserimento = adataInserimento;
    return this;
  }

   /**
   * Get adataInserimento
   * @return adataInserimento
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getAdataInserimento() {
    return adataInserimento;
  }

  public void setAdataInserimento(OffsetDateTime adataInserimento) {
    this.adataInserimento = adataInserimento;
  }

  public CriteriRicercaDto adataLimitePagabilita(OffsetDateTime adataLimitePagabilita) {
    this.adataLimitePagabilita = adataLimitePagabilita;
    return this;
  }

   /**
   * Get adataLimitePagabilita
   * @return adataLimitePagabilita
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getAdataLimitePagabilita() {
    return adataLimitePagabilita;
  }

  public void setAdataLimitePagabilita(OffsetDateTime adataLimitePagabilita) {
    this.adataLimitePagabilita = adataLimitePagabilita;
  }

  public CriteriRicercaDto codiceIpa(String codiceIpa) {
    this.codiceIpa = codiceIpa;
    return this;
  }

   /**
   * Codice IPA identificativo dell’ente
   * @return codiceIpa
  **/
  @ApiModelProperty(example = "EntTest1", value = "Codice IPA identificativo dell’ente")
  public String getCodiceIpa() {
    return codiceIpa;
  }

  public void setCodiceIpa(String codiceIpa) {
    this.codiceIpa = codiceIpa;
  }

  public CriteriRicercaDto codiceTipoDebito(String codiceTipoDebito) {
    this.codiceTipoDebito = codiceTipoDebito;
    return this;
  }

   /**
   * Codice che identifica il tipo debito da ricercare
   * @return codiceTipoDebito
  **/
  @ApiModelProperty(example = "MULTE", required = true, value = "Codice che identifica il tipo debito da ricercare")
  public String getCodiceTipoDebito() {
    return codiceTipoDebito;
  }

  public void setCodiceTipoDebito(String codiceTipoDebito) {
    this.codiceTipoDebito = codiceTipoDebito;
  }

  public CriteriRicercaDto contribuente(ContribuenteDebitoDto contribuente) {
    this.contribuente = contribuente;
    return this;
  }

   /**
   * Tipo complesso che racchiude le info principali sul soggetto debitore
   * @return contribuente
  **/
  @ApiModelProperty(required = true, value = "Tipo complesso che racchiude le info principali sul soggetto debitore")
  public ContribuenteDebitoDto getContribuente() {
    return contribuente;
  }

  public void setContribuente(ContribuenteDebitoDto contribuente) {
    this.contribuente = contribuente;
  }

  public CriteriRicercaDto daDataFineValidita(OffsetDateTime daDataFineValidita) {
    this.daDataFineValidita = daDataFineValidita;
    return this;
  }

   /**
   * Data che descrive l’inizio del periodo di fine validità dei debiti ricercati
   * @return daDataFineValidita
  **/
  @ApiModelProperty(example = "2023-01-01T00:00:00Z", value = "Data che descrive l’inizio del periodo di fine validità dei debiti ricercati")
  public OffsetDateTime getDaDataFineValidita() {
    return daDataFineValidita;
  }

  public void setDaDataFineValidita(OffsetDateTime daDataFineValidita) {
    this.daDataFineValidita = daDataFineValidita;
  }

  public CriteriRicercaDto daDataInizioValidita(OffsetDateTime daDataInizioValidita) {
    this.daDataInizioValidita = daDataInizioValidita;
    return this;
  }

   /**
   * Data che descrive l’inizio del periodo di inizio validità dei debiti ricercati
   * @return daDataInizioValidita
  **/
  @ApiModelProperty(example = "2023-01-02T00:00:00Z", value = "Data che descrive l’inizio del periodo di inizio validità dei debiti ricercati")
  public OffsetDateTime getDaDataInizioValidita() {
    return daDataInizioValidita;
  }

  public void setDaDataInizioValidita(OffsetDateTime daDataInizioValidita) {
    this.daDataInizioValidita = daDataInizioValidita;
  }

  public CriteriRicercaDto daDataInserimento(OffsetDateTime daDataInserimento) {
    this.daDataInserimento = daDataInserimento;
    return this;
  }

   /**
   * Data che descrive l’inizio del periodo in cui i debiti sono stati inseriti
   * @return daDataInserimento
  **/
  @ApiModelProperty(example = "2023-01-01T00:00:00Z", value = "Data che descrive l’inizio del periodo in cui i debiti sono stati inseriti")
  public OffsetDateTime getDaDataInserimento() {
    return daDataInserimento;
  }

  public void setDaDataInserimento(OffsetDateTime daDataInserimento) {
    this.daDataInserimento = daDataInserimento;
  }

  public CriteriRicercaDto daDataLimitePagabilita(OffsetDateTime daDataLimitePagabilita) {
    this.daDataLimitePagabilita = daDataLimitePagabilita;
    return this;
  }

   /**
   * Data che descrive l’inizio del periodo di limite pagabilità dei debiti ricercati
   * @return daDataLimitePagabilita
  **/
  @ApiModelProperty(example = "2023-01-01T00:00:00Z", value = "Data che descrive l’inizio del periodo di limite pagabilità dei debiti ricercati")
  public OffsetDateTime getDaDataLimitePagabilita() {
    return daDataLimitePagabilita;
  }

  public void setDaDataLimitePagabilita(OffsetDateTime daDataLimitePagabilita) {
    this.daDataLimitePagabilita = daDataLimitePagabilita;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CriteriRicercaDto criteriRicercaDto = (CriteriRicercaDto) o;
    return Objects.equals(this.adataFineValidita, criteriRicercaDto.adataFineValidita) &&
        Objects.equals(this.adataInizioValidita, criteriRicercaDto.adataInizioValidita) &&
        Objects.equals(this.adataInserimento, criteriRicercaDto.adataInserimento) &&
        Objects.equals(this.adataLimitePagabilita, criteriRicercaDto.adataLimitePagabilita) &&
        Objects.equals(this.codiceIpa, criteriRicercaDto.codiceIpa) &&
        Objects.equals(this.codiceTipoDebito, criteriRicercaDto.codiceTipoDebito) &&
        Objects.equals(this.contribuente, criteriRicercaDto.contribuente) &&
        Objects.equals(this.daDataFineValidita, criteriRicercaDto.daDataFineValidita) &&
        Objects.equals(this.daDataInizioValidita, criteriRicercaDto.daDataInizioValidita) &&
        Objects.equals(this.daDataInserimento, criteriRicercaDto.daDataInserimento) &&
        Objects.equals(this.daDataLimitePagabilita, criteriRicercaDto.daDataLimitePagabilita);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adataFineValidita, adataInizioValidita, adataInserimento, adataLimitePagabilita, codiceIpa, codiceTipoDebito, contribuente, daDataFineValidita, daDataInizioValidita, daDataInserimento, daDataLimitePagabilita);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CriteriRicercaDto {\n");
    
    sb.append("    adataFineValidita: ").append(toIndentedString(adataFineValidita)).append("\n");
    sb.append("    adataInizioValidita: ").append(toIndentedString(adataInizioValidita)).append("\n");
    sb.append("    adataInserimento: ").append(toIndentedString(adataInserimento)).append("\n");
    sb.append("    adataLimitePagabilita: ").append(toIndentedString(adataLimitePagabilita)).append("\n");
    sb.append("    codiceIpa: ").append(toIndentedString(codiceIpa)).append("\n");
    sb.append("    codiceTipoDebito: ").append(toIndentedString(codiceTipoDebito)).append("\n");
    sb.append("    contribuente: ").append(toIndentedString(contribuente)).append("\n");
    sb.append("    daDataFineValidita: ").append(toIndentedString(daDataFineValidita)).append("\n");
    sb.append("    daDataInizioValidita: ").append(toIndentedString(daDataInizioValidita)).append("\n");
    sb.append("    daDataInserimento: ").append(toIndentedString(daDataInserimento)).append("\n");
    sb.append("    daDataLimitePagabilita: ").append(toIndentedString(daDataLimitePagabilita)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

