/*
 * API Gateway Pagamenti
 * Set API REST PagoPA
 *
 * OpenAPI spec version: 1.0
 * Contact: pagamenti.produzione@maggioli.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CtEsito;
import java.io.IOException;

/**
 * CtAttivaAvvisoPerIdLottoResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-23T07:57:29.055Z")
public class CtAttivaAvvisoPerIdLottoResult {
  @SerializedName("esito")
  private CtEsito esito = null;

  public CtAttivaAvvisoPerIdLottoResult esito(CtEsito esito) {
    this.esito = esito;
    return this;
  }

   /**
   * Get esito
   * @return esito
  **/
  @ApiModelProperty(value = "")
  public CtEsito getEsito() {
    return esito;
  }

  public void setEsito(CtEsito esito) {
    this.esito = esito;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CtAttivaAvvisoPerIdLottoResult ctAttivaAvvisoPerIdLottoResult = (CtAttivaAvvisoPerIdLottoResult) o;
    return Objects.equals(this.esito, ctAttivaAvvisoPerIdLottoResult.esito);
  }

  @Override
  public int hashCode() {
    return Objects.hash(esito);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CtAttivaAvvisoPerIdLottoResult {\n");
    
    sb.append("    esito: ").append(toIndentedString(esito)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

