/*
 * API Gateway Pagamenti
 * Set API REST PagoPA
 *
 * OpenAPI spec version: 1.0
 * Contact: pagamenti.produzione@maggioli.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CtChiaveDebito
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-23T07:57:29.055Z")
public class CtChiaveDebito {
  @SerializedName("codiceTipoDebito")
  private String codiceTipoDebito = null;

  @SerializedName("iddeb")
  private String iddeb = null;

  @SerializedName("idpos")
  private String idpos = null;

  public CtChiaveDebito codiceTipoDebito(String codiceTipoDebito) {
    this.codiceTipoDebito = codiceTipoDebito;
    return this;
  }

   /**
   * Get codiceTipoDebito
   * @return codiceTipoDebito
  **/
  @ApiModelProperty(value = "")
  public String getCodiceTipoDebito() {
    return codiceTipoDebito;
  }

  public void setCodiceTipoDebito(String codiceTipoDebito) {
    this.codiceTipoDebito = codiceTipoDebito;
  }

  public CtChiaveDebito iddeb(String iddeb) {
    this.iddeb = iddeb;
    return this;
  }

   /**
   * Get iddeb
   * @return iddeb
  **/
  @ApiModelProperty(value = "")
  public String getIddeb() {
    return iddeb;
  }

  public void setIddeb(String iddeb) {
    this.iddeb = iddeb;
  }

  public CtChiaveDebito idpos(String idpos) {
    this.idpos = idpos;
    return this;
  }

   /**
   * Get idpos
   * @return idpos
  **/
  @ApiModelProperty(value = "")
  public String getIdpos() {
    return idpos;
  }

  public void setIdpos(String idpos) {
    this.idpos = idpos;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CtChiaveDebito ctChiaveDebito = (CtChiaveDebito) o;
    return Objects.equals(this.codiceTipoDebito, ctChiaveDebito.codiceTipoDebito) &&
        Objects.equals(this.iddeb, ctChiaveDebito.iddeb) &&
        Objects.equals(this.idpos, ctChiaveDebito.idpos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codiceTipoDebito, iddeb, idpos);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CtChiaveDebito {\n");
    
    sb.append("    codiceTipoDebito: ").append(toIndentedString(codiceTipoDebito)).append("\n");
    sb.append("    iddeb: ").append(toIndentedString(iddeb)).append("\n");
    sb.append("    idpos: ").append(toIndentedString(idpos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

