/*
 * API Gateway Pagamenti
 * Set API REST PagoPA
 *
 * OpenAPI spec version: 1.0
 * Contact: pagamenti.produzione@maggioli.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CtNumeroAvviso
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-23T07:57:29.055Z")
public class CtNumeroAvviso {
  @SerializedName("flagAttivaDebito")
  private Boolean flagAttivaDebito = null;

  @SerializedName("value")
  private String value = null;

  @SerializedName("versioneNumeroAvviso")
  private Integer versioneNumeroAvviso = null;

  public CtNumeroAvviso flagAttivaDebito(Boolean flagAttivaDebito) {
    this.flagAttivaDebito = flagAttivaDebito;
    return this;
  }

   /**
   * Get flagAttivaDebito
   * @return flagAttivaDebito
  **/
  @ApiModelProperty(value = "")
  public Boolean isFlagAttivaDebito() {
    return flagAttivaDebito;
  }

  public void setFlagAttivaDebito(Boolean flagAttivaDebito) {
    this.flagAttivaDebito = flagAttivaDebito;
  }

  public CtNumeroAvviso value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(value = "")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public CtNumeroAvviso versioneNumeroAvviso(Integer versioneNumeroAvviso) {
    this.versioneNumeroAvviso = versioneNumeroAvviso;
    return this;
  }

   /**
   * Get versioneNumeroAvviso
   * @return versioneNumeroAvviso
  **/
  @ApiModelProperty(value = "")
  public Integer getVersioneNumeroAvviso() {
    return versioneNumeroAvviso;
  }

  public void setVersioneNumeroAvviso(Integer versioneNumeroAvviso) {
    this.versioneNumeroAvviso = versioneNumeroAvviso;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CtNumeroAvviso ctNumeroAvviso = (CtNumeroAvviso) o;
    return Objects.equals(this.flagAttivaDebito, ctNumeroAvviso.flagAttivaDebito) &&
        Objects.equals(this.value, ctNumeroAvviso.value) &&
        Objects.equals(this.versioneNumeroAvviso, ctNumeroAvviso.versioneNumeroAvviso);
  }

  @Override
  public int hashCode() {
    return Objects.hash(flagAttivaDebito, value, versioneNumeroAvviso);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CtNumeroAvviso {\n");
    
    sb.append("    flagAttivaDebito: ").append(toIndentedString(flagAttivaDebito)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    versioneNumeroAvviso: ").append(toIndentedString(versioneNumeroAvviso)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

