/*
 * API Gateway Pagamenti
 * Set API REST PagoPA
 *
 * OpenAPI spec version: 1.0
 * Contact: pagamenti.produzione@maggioli.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ChiaveDebitoDto;
import io.swagger.client.model.DatoAccertamentoDto;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * DebitoRiconcilaitoDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-23T07:57:29.055Z")
public class DebitoRiconcilaitoDto {
  @SerializedName("chiavidebito")
  private ChiaveDebitoDto chiavidebito = null;

  @SerializedName("datiAccertamento")
  private List<DatoAccertamentoDto> datiAccertamento = null;

  @SerializedName("importoDebito")
  private BigDecimal importoDebito = null;

  public DebitoRiconcilaitoDto chiavidebito(ChiaveDebitoDto chiavidebito) {
    this.chiavidebito = chiavidebito;
    return this;
  }

   /**
   * Get chiavidebito
   * @return chiavidebito
  **/
  @ApiModelProperty(value = "")
  public ChiaveDebitoDto getChiavidebito() {
    return chiavidebito;
  }

  public void setChiavidebito(ChiaveDebitoDto chiavidebito) {
    this.chiavidebito = chiavidebito;
  }

  public DebitoRiconcilaitoDto datiAccertamento(List<DatoAccertamentoDto> datiAccertamento) {
    this.datiAccertamento = datiAccertamento;
    return this;
  }

  public DebitoRiconcilaitoDto addDatiAccertamentoItem(DatoAccertamentoDto datiAccertamentoItem) {
    if (this.datiAccertamento == null) {
      this.datiAccertamento = new ArrayList<DatoAccertamentoDto>();
    }
    this.datiAccertamento.add(datiAccertamentoItem);
    return this;
  }

   /**
   * Get datiAccertamento
   * @return datiAccertamento
  **/
  @ApiModelProperty(value = "")
  public List<DatoAccertamentoDto> getDatiAccertamento() {
    return datiAccertamento;
  }

  public void setDatiAccertamento(List<DatoAccertamentoDto> datiAccertamento) {
    this.datiAccertamento = datiAccertamento;
  }

  public DebitoRiconcilaitoDto importoDebito(BigDecimal importoDebito) {
    this.importoDebito = importoDebito;
    return this;
  }

   /**
   * Get importoDebito
   * @return importoDebito
  **/
  @ApiModelProperty(example = "59.99", value = "")
  public BigDecimal getImportoDebito() {
    return importoDebito;
  }

  public void setImportoDebito(BigDecimal importoDebito) {
    this.importoDebito = importoDebito;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DebitoRiconcilaitoDto debitoRiconcilaitoDto = (DebitoRiconcilaitoDto) o;
    return Objects.equals(this.chiavidebito, debitoRiconcilaitoDto.chiavidebito) &&
        Objects.equals(this.datiAccertamento, debitoRiconcilaitoDto.datiAccertamento) &&
        Objects.equals(this.importoDebito, debitoRiconcilaitoDto.importoDebito);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chiavidebito, datiAccertamento, importoDebito);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DebitoRiconcilaitoDto {\n");
    
    sb.append("    chiavidebito: ").append(toIndentedString(chiavidebito)).append("\n");
    sb.append("    datiAccertamento: ").append(toIndentedString(datiAccertamento)).append("\n");
    sb.append("    importoDebito: ").append(toIndentedString(importoDebito)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

