/*
 * API Gateway Pagamenti
 * Set API REST PagoPA
 *
 * OpenAPI spec version: 1.0
 * Contact: pagamenti.produzione@maggioli.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ChiaveDebitoDto;
import java.io.IOException;

/**
 * DebitoPagatoDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-23T07:57:29.055Z")
public class DebitoPagatoDto {
  @SerializedName("chiaviDebito")
  private ChiaveDebitoDto chiaviDebito = null;

  @SerializedName("identificativoUnivocoVersamento")
  private String identificativoUnivocoVersamento = null;

  /**
   * Gets or Sets modalitaPagamento
   */
  @JsonAdapter(ModalitaPagamentoEnum.Adapter.class)
  public enum ModalitaPagamentoEnum {
    MOD1("MOD1"),
    
    MOD3("MOD3");

    private String value;

    ModalitaPagamentoEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ModalitaPagamentoEnum fromValue(String text) {
      for (ModalitaPagamentoEnum b : ModalitaPagamentoEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<ModalitaPagamentoEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ModalitaPagamentoEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ModalitaPagamentoEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ModalitaPagamentoEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("modalitaPagamento")
  private ModalitaPagamentoEnum modalitaPagamento = null;

  /**
   * Gets or Sets statoPagamento
   */
  @JsonAdapter(StatoPagamentoEnum.Adapter.class)
  public enum StatoPagamentoEnum {
    CONTABILIZZATO("CONTABILIZZATO"),
    
    NOTIFICATO("NOTIFICATO");

    private String value;

    StatoPagamentoEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatoPagamentoEnum fromValue(String text) {
      for (StatoPagamentoEnum b : StatoPagamentoEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StatoPagamentoEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatoPagamentoEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatoPagamentoEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatoPagamentoEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("statoPagamento")
  private StatoPagamentoEnum statoPagamento = null;

  public DebitoPagatoDto chiaviDebito(ChiaveDebitoDto chiaviDebito) {
    this.chiaviDebito = chiaviDebito;
    return this;
  }

   /**
   * Get chiaviDebito
   * @return chiaviDebito
  **/
  @ApiModelProperty(value = "")
  public ChiaveDebitoDto getChiaviDebito() {
    return chiaviDebito;
  }

  public void setChiaviDebito(ChiaveDebitoDto chiaviDebito) {
    this.chiaviDebito = chiaviDebito;
  }

  public DebitoPagatoDto identificativoUnivocoVersamento(String identificativoUnivocoVersamento) {
    this.identificativoUnivocoVersamento = identificativoUnivocoVersamento;
    return this;
  }

   /**
   * Identificativo Univoco Versamento, attribuito dall&#39;Ente Creditore ad ogni operazione di incasso e che non può essere associato nel tempo ad alcun altro incasso emesso dal medesimo Ente Creditore, max 25 caratteri
   * @return identificativoUnivocoVersamento
  **/
  @ApiModelProperty(example = "04210009695360182", required = true, value = "Identificativo Univoco Versamento, attribuito dall'Ente Creditore ad ogni operazione di incasso e che non può essere associato nel tempo ad alcun altro incasso emesso dal medesimo Ente Creditore, max 25 caratteri")
  public String getIdentificativoUnivocoVersamento() {
    return identificativoUnivocoVersamento;
  }

  public void setIdentificativoUnivocoVersamento(String identificativoUnivocoVersamento) {
    this.identificativoUnivocoVersamento = identificativoUnivocoVersamento;
  }

  public DebitoPagatoDto modalitaPagamento(ModalitaPagamentoEnum modalitaPagamento) {
    this.modalitaPagamento = modalitaPagamento;
    return this;
  }

   /**
   * Get modalitaPagamento
   * @return modalitaPagamento
  **/
  @ApiModelProperty(value = "")
  public ModalitaPagamentoEnum getModalitaPagamento() {
    return modalitaPagamento;
  }

  public void setModalitaPagamento(ModalitaPagamentoEnum modalitaPagamento) {
    this.modalitaPagamento = modalitaPagamento;
  }

  public DebitoPagatoDto statoPagamento(StatoPagamentoEnum statoPagamento) {
    this.statoPagamento = statoPagamento;
    return this;
  }

   /**
   * Get statoPagamento
   * @return statoPagamento
  **/
  @ApiModelProperty(value = "")
  public StatoPagamentoEnum getStatoPagamento() {
    return statoPagamento;
  }

  public void setStatoPagamento(StatoPagamentoEnum statoPagamento) {
    this.statoPagamento = statoPagamento;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DebitoPagatoDto debitoPagatoDto = (DebitoPagatoDto) o;
    return Objects.equals(this.chiaviDebito, debitoPagatoDto.chiaviDebito) &&
        Objects.equals(this.identificativoUnivocoVersamento, debitoPagatoDto.identificativoUnivocoVersamento) &&
        Objects.equals(this.modalitaPagamento, debitoPagatoDto.modalitaPagamento) &&
        Objects.equals(this.statoPagamento, debitoPagatoDto.statoPagamento);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chiaviDebito, identificativoUnivocoVersamento, modalitaPagamento, statoPagamento);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DebitoPagatoDto {\n");
    
    sb.append("    chiaviDebito: ").append(toIndentedString(chiaviDebito)).append("\n");
    sb.append("    identificativoUnivocoVersamento: ").append(toIndentedString(identificativoUnivocoVersamento)).append("\n");
    sb.append("    modalitaPagamento: ").append(toIndentedString(modalitaPagamento)).append("\n");
    sb.append("    statoPagamento: ").append(toIndentedString(statoPagamento)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

