/*
 * API Gateway Pagamenti
 * Set API REST PagoPA
 *
 * OpenAPI spec version: 1.0
 * Contact: pagamenti.produzione@maggioli.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Nodo in cui verranno riportati tutti i dettagli in cui è scomposto l’importo del debito in capitoli di bilancio o alternativamente in tipi voce. Può essere nullo in caso per quel tipo debito non sia stato definito un tipo voce o capitolo di default
 */
@ApiModel(description = "Nodo in cui verranno riportati tutti i dettagli in cui è scomposto l’importo del debito in capitoli di bilancio o alternativamente in tipi voce. Può essere nullo in caso per quel tipo debito non sia stato definito un tipo voce o capitolo di default")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-23T07:57:29.055Z")
public class DettaglioImportoDto {
  @SerializedName("anno")
  private String anno = null;

  @SerializedName("capitoloBilancio")
  private String capitoloBilancio = null;

  @SerializedName("codice")
  private String codice = null;

  @SerializedName("descrizione")
  private String descrizione = null;

  @SerializedName("importo")
  private Double importo = null;

  public DettaglioImportoDto anno(String anno) {
    this.anno = anno;
    return this;
  }

   /**
   * Get anno
   * @return anno
  **/
  @ApiModelProperty(value = "")
  public String getAnno() {
    return anno;
  }

  public void setAnno(String anno) {
    this.anno = anno;
  }

  public DettaglioImportoDto capitoloBilancio(String capitoloBilancio) {
    this.capitoloBilancio = capitoloBilancio;
    return this;
  }

   /**
   * Get capitoloBilancio
   * @return capitoloBilancio
  **/
  @ApiModelProperty(value = "")
  public String getCapitoloBilancio() {
    return capitoloBilancio;
  }

  public void setCapitoloBilancio(String capitoloBilancio) {
    this.capitoloBilancio = capitoloBilancio;
  }

  public DettaglioImportoDto codice(String codice) {
    this.codice = codice;
    return this;
  }

   /**
   * Get codice
   * @return codice
  **/
  @ApiModelProperty(value = "")
  public String getCodice() {
    return codice;
  }

  public void setCodice(String codice) {
    this.codice = codice;
  }

  public DettaglioImportoDto descrizione(String descrizione) {
    this.descrizione = descrizione;
    return this;
  }

   /**
   * Get descrizione
   * @return descrizione
  **/
  @ApiModelProperty(value = "")
  public String getDescrizione() {
    return descrizione;
  }

  public void setDescrizione(String descrizione) {
    this.descrizione = descrizione;
  }

  public DettaglioImportoDto importo(Double importo) {
    this.importo = importo;
    return this;
  }

   /**
   * Get importo
   * @return importo
  **/
  @ApiModelProperty(value = "")
  public Double getImporto() {
    return importo;
  }

  public void setImporto(Double importo) {
    this.importo = importo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DettaglioImportoDto dettaglioImportoDto = (DettaglioImportoDto) o;
    return Objects.equals(this.anno, dettaglioImportoDto.anno) &&
        Objects.equals(this.capitoloBilancio, dettaglioImportoDto.capitoloBilancio) &&
        Objects.equals(this.codice, dettaglioImportoDto.codice) &&
        Objects.equals(this.descrizione, dettaglioImportoDto.descrizione) &&
        Objects.equals(this.importo, dettaglioImportoDto.importo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(anno, capitoloBilancio, codice, descrizione, importo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DettaglioImportoDto {\n");
    
    sb.append("    anno: ").append(toIndentedString(anno)).append("\n");
    sb.append("    capitoloBilancio: ").append(toIndentedString(capitoloBilancio)).append("\n");
    sb.append("    codice: ").append(toIndentedString(codice)).append("\n");
    sb.append("    descrizione: ").append(toIndentedString(descrizione)).append("\n");
    sb.append("    importo: ").append(toIndentedString(importo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

