/*
 * API Gateway Pagamenti
 * Set API REST PagoPA
 *
 * OpenAPI spec version: 1.0
 * Contact: pagamenti.produzione@maggioli.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DebitoEstrattoContoDto;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * EstrattoContoDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-23T07:57:29.055Z")
public class EstrattoContoDto {
  @SerializedName("debiti")
  private List<DebitoEstrattoContoDto> debiti = null;

  @SerializedName("numeroTotaleDiElementi")
  private Long numeroTotaleDiElementi = null;

  public EstrattoContoDto debiti(List<DebitoEstrattoContoDto> debiti) {
    this.debiti = debiti;
    return this;
  }

  public EstrattoContoDto addDebitiItem(DebitoEstrattoContoDto debitiItem) {
    if (this.debiti == null) {
      this.debiti = new ArrayList<DebitoEstrattoContoDto>();
    }
    this.debiti.add(debitiItem);
    return this;
  }

   /**
   * Get debiti
   * @return debiti
  **/
  @ApiModelProperty(value = "")
  public List<DebitoEstrattoContoDto> getDebiti() {
    return debiti;
  }

  public void setDebiti(List<DebitoEstrattoContoDto> debiti) {
    this.debiti = debiti;
  }

  public EstrattoContoDto numeroTotaleDiElementi(Long numeroTotaleDiElementi) {
    this.numeroTotaleDiElementi = numeroTotaleDiElementi;
    return this;
  }

   /**
   * Numero totale di elementi trovati in archivio
   * @return numeroTotaleDiElementi
  **/
  @ApiModelProperty(value = "Numero totale di elementi trovati in archivio")
  public Long getNumeroTotaleDiElementi() {
    return numeroTotaleDiElementi;
  }

  public void setNumeroTotaleDiElementi(Long numeroTotaleDiElementi) {
    this.numeroTotaleDiElementi = numeroTotaleDiElementi;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EstrattoContoDto estrattoContoDto = (EstrattoContoDto) o;
    return Objects.equals(this.debiti, estrattoContoDto.debiti) &&
        Objects.equals(this.numeroTotaleDiElementi, estrattoContoDto.numeroTotaleDiElementi);
  }

  @Override
  public int hashCode() {
    return Objects.hash(debiti, numeroTotaleDiElementi);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EstrattoContoDto {\n");
    
    sb.append("    debiti: ").append(toIndentedString(debiti)).append("\n");
    sb.append("    numeroTotaleDiElementi: ").append(toIndentedString(numeroTotaleDiElementi)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

