/*
 * API Gateway Pagamenti
 * Set API REST PagoPA
 *
 * OpenAPI spec version: 1.0
 * Contact: pagamenti.produzione@maggioli.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ChiaveDebitoDto;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * InfoMultibeneficiarioDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-23T07:57:29.055Z")
public class InfoMultibeneficiarioDto {
  @SerializedName("chiaviDebito")
  private ChiaveDebitoDto chiaviDebito = null;

  @SerializedName("codiceIpa")
  private String codiceIpa = null;

  @SerializedName("importo")
  private BigDecimal importo = null;

  public InfoMultibeneficiarioDto chiaviDebito(ChiaveDebitoDto chiaviDebito) {
    this.chiaviDebito = chiaviDebito;
    return this;
  }

   /**
   * Get chiaviDebito
   * @return chiaviDebito
  **/
  @ApiModelProperty(value = "")
  public ChiaveDebitoDto getChiaviDebito() {
    return chiaviDebito;
  }

  public void setChiaviDebito(ChiaveDebitoDto chiaviDebito) {
    this.chiaviDebito = chiaviDebito;
  }

  public InfoMultibeneficiarioDto codiceIpa(String codiceIpa) {
    this.codiceIpa = codiceIpa;
    return this;
  }

   /**
   * Codice IPA identificativo dell’ente
   * @return codiceIpa
  **/
  @ApiModelProperty(example = "EntTest1", value = "Codice IPA identificativo dell’ente")
  public String getCodiceIpa() {
    return codiceIpa;
  }

  public void setCodiceIpa(String codiceIpa) {
    this.codiceIpa = codiceIpa;
  }

  public InfoMultibeneficiarioDto importo(BigDecimal importo) {
    this.importo = importo;
    return this;
  }

   /**
   * Get importo
   * @return importo
  **/
  @ApiModelProperty(example = "59.99", value = "")
  public BigDecimal getImporto() {
    return importo;
  }

  public void setImporto(BigDecimal importo) {
    this.importo = importo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InfoMultibeneficiarioDto infoMultibeneficiarioDto = (InfoMultibeneficiarioDto) o;
    return Objects.equals(this.chiaviDebito, infoMultibeneficiarioDto.chiaviDebito) &&
        Objects.equals(this.codiceIpa, infoMultibeneficiarioDto.codiceIpa) &&
        Objects.equals(this.importo, infoMultibeneficiarioDto.importo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chiaviDebito, codiceIpa, importo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InfoMultibeneficiarioDto {\n");
    
    sb.append("    chiaviDebito: ").append(toIndentedString(chiaviDebito)).append("\n");
    sb.append("    codiceIpa: ").append(toIndentedString(codiceIpa)).append("\n");
    sb.append("    importo: ").append(toIndentedString(importo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

