/*
 * API Gateway Pagamenti
 * Set API REST PagoPA
 *
 * OpenAPI spec version: 1.0
 * Contact: pagamenti.produzione@maggioli.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DatiDebitoreDto;
import io.swagger.client.model.DatiVersanteDto;
import io.swagger.client.model.InfoSingoloPagamentoDto;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * Oggetto che identifica il pagamento (RPT) eseguito
 */
@ApiModel(description = "Oggetto che identifica il pagamento (RPT) eseguito")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-23T07:57:29.055Z")
public class InfoPagamentoTelematicoDto {
  /**
   * Gets or Sets codiceContestoPagamento
   */
  @JsonAdapter(CodiceContestoPagamentoEnum.Adapter.class)
  public enum CodiceContestoPagamentoEnum {
    CCP_TMP_PSPPA("CCP_TMP_PSPPA"),
    
    N_A("N/A");

    private String value;

    CodiceContestoPagamentoEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CodiceContestoPagamentoEnum fromValue(String text) {
      for (CodiceContestoPagamentoEnum b : CodiceContestoPagamentoEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<CodiceContestoPagamentoEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CodiceContestoPagamentoEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CodiceContestoPagamentoEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return CodiceContestoPagamentoEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("codiceContestoPagamento")
  private CodiceContestoPagamentoEnum codiceContestoPagamento = null;

  @SerializedName("dataAccredito")
  private OffsetDateTime dataAccredito = null;

  @SerializedName("dataPagamento")
  private OffsetDateTime dataPagamento = null;

  @SerializedName("datiDebitore")
  private DatiDebitoreDto datiDebitore = null;

  @SerializedName("datiVersante")
  private DatiVersanteDto datiVersante = null;

  /**
   * Gets or Sets esitoRichiestaPagamento
   */
  @JsonAdapter(EsitoRichiestaPagamentoEnum.Adapter.class)
  public enum EsitoRichiestaPagamentoEnum {
    CONCLUSO_ESEGUITO("CONCLUSO_ESEGUITO"),
    
    CONCLUSO_ESEGUITO_PARZIALMENTE("CONCLUSO_ESEGUITO_PARZIALMENTE"),
    
    CONCLUSO_NON_ESEGUITO("CONCLUSO_NON_ESEGUITO"),
    
    CONCLUSO_NON_ESEGUITO_DECORRENZA("CONCLUSO_NON_ESEGUITO_DECORRENZA"),
    
    CONCLUSO_NON_ESEGUITO_DECORRENZA_PARZIALE("CONCLUSO_NON_ESEGUITO_DECORRENZA_PARZIALE"),
    
    NON_CONCLUSO("NON_CONCLUSO"),
    
    RIFIUTATA("RIFIUTATA");

    private String value;

    EsitoRichiestaPagamentoEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static EsitoRichiestaPagamentoEnum fromValue(String text) {
      for (EsitoRichiestaPagamentoEnum b : EsitoRichiestaPagamentoEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<EsitoRichiestaPagamentoEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final EsitoRichiestaPagamentoEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public EsitoRichiestaPagamentoEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return EsitoRichiestaPagamentoEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("esitoRichiestaPagamento")
  private EsitoRichiestaPagamentoEnum esitoRichiestaPagamento = null;

  @SerializedName("flussoRicevuta")
  private String flussoRicevuta = null;

  @SerializedName("identificativoDominio")
  private String identificativoDominio = null;

  @SerializedName("identificativoUnivocoVersamento")
  private String identificativoUnivocoVersamento = null;

  @SerializedName("importoTotalePagato")
  private BigDecimal importoTotalePagato = null;

  @SerializedName("importoTotaleRichiesta")
  private BigDecimal importoTotaleRichiesta = null;

  @SerializedName("infoVersamentoSingolo")
  private List<InfoSingoloPagamentoDto> infoVersamentoSingolo = null;

  @SerializedName("numeroAvviso")
  private String numeroAvviso = null;

  @SerializedName("numeroVersamentiSingoli")
  private Integer numeroVersamentiSingoli = null;

  /**
   * Gets or Sets statoTecnicoPagamento
   */
  @JsonAdapter(StatoTecnicoPagamentoEnum.Adapter.class)
  public enum StatoTecnicoPagamentoEnum {
    COMPLETATO("COMPLETATO"),
    
    CONTABILIZZATO("CONTABILIZZATO"),
    
    INVIATO("INVIATO"),
    
    NOTIFICATO("NOTIFICATO"),
    
    RIFIUTATO("RIFIUTATO");

    private String value;

    StatoTecnicoPagamentoEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatoTecnicoPagamentoEnum fromValue(String text) {
      for (StatoTecnicoPagamentoEnum b : StatoTecnicoPagamentoEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StatoTecnicoPagamentoEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatoTecnicoPagamentoEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatoTecnicoPagamentoEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatoTecnicoPagamentoEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("statoTecnicoPagamento")
  private StatoTecnicoPagamentoEnum statoTecnicoPagamento = null;

  @SerializedName("testoOriginaleRicevuta")
  private String testoOriginaleRicevuta = null;

  /**
   * Gets or Sets tipoVersamento
   */
  @JsonAdapter(TipoVersamentoEnum.Adapter.class)
  public enum TipoVersamentoEnum {
    AD("AD"),
    
    BBT("BBT"),
    
    BP("BP"),
    
    CP("CP"),
    
    INDETERMINATO("INDETERMINATO"),
    
    OBEP("OBEP"),
    
    PO("PO");

    private String value;

    TipoVersamentoEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TipoVersamentoEnum fromValue(String text) {
      for (TipoVersamentoEnum b : TipoVersamentoEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<TipoVersamentoEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TipoVersamentoEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TipoVersamentoEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return TipoVersamentoEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("tipoVersamento")
  private TipoVersamentoEnum tipoVersamento = null;

  public InfoPagamentoTelematicoDto codiceContestoPagamento(CodiceContestoPagamentoEnum codiceContestoPagamento) {
    this.codiceContestoPagamento = codiceContestoPagamento;
    return this;
  }

   /**
   * Get codiceContestoPagamento
   * @return codiceContestoPagamento
  **/
  @ApiModelProperty(example = "N/A", value = "")
  public CodiceContestoPagamentoEnum getCodiceContestoPagamento() {
    return codiceContestoPagamento;
  }

  public void setCodiceContestoPagamento(CodiceContestoPagamentoEnum codiceContestoPagamento) {
    this.codiceContestoPagamento = codiceContestoPagamento;
  }

  public InfoPagamentoTelematicoDto dataAccredito(OffsetDateTime dataAccredito) {
    this.dataAccredito = dataAccredito;
    return this;
  }

   /**
   * Get dataAccredito
   * @return dataAccredito
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDataAccredito() {
    return dataAccredito;
  }

  public void setDataAccredito(OffsetDateTime dataAccredito) {
    this.dataAccredito = dataAccredito;
  }

  public InfoPagamentoTelematicoDto dataPagamento(OffsetDateTime dataPagamento) {
    this.dataPagamento = dataPagamento;
    return this;
  }

   /**
   * Get dataPagamento
   * @return dataPagamento
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDataPagamento() {
    return dataPagamento;
  }

  public void setDataPagamento(OffsetDateTime dataPagamento) {
    this.dataPagamento = dataPagamento;
  }

  public InfoPagamentoTelematicoDto datiDebitore(DatiDebitoreDto datiDebitore) {
    this.datiDebitore = datiDebitore;
    return this;
  }

   /**
   * Get datiDebitore
   * @return datiDebitore
  **/
  @ApiModelProperty(value = "")
  public DatiDebitoreDto getDatiDebitore() {
    return datiDebitore;
  }

  public void setDatiDebitore(DatiDebitoreDto datiDebitore) {
    this.datiDebitore = datiDebitore;
  }

  public InfoPagamentoTelematicoDto datiVersante(DatiVersanteDto datiVersante) {
    this.datiVersante = datiVersante;
    return this;
  }

   /**
   * Get datiVersante
   * @return datiVersante
  **/
  @ApiModelProperty(value = "")
  public DatiVersanteDto getDatiVersante() {
    return datiVersante;
  }

  public void setDatiVersante(DatiVersanteDto datiVersante) {
    this.datiVersante = datiVersante;
  }

  public InfoPagamentoTelematicoDto esitoRichiestaPagamento(EsitoRichiestaPagamentoEnum esitoRichiestaPagamento) {
    this.esitoRichiestaPagamento = esitoRichiestaPagamento;
    return this;
  }

   /**
   * Get esitoRichiestaPagamento
   * @return esitoRichiestaPagamento
  **/
  @ApiModelProperty(example = "CONCLUSO_NON_ESEGUITO", value = "")
  public EsitoRichiestaPagamentoEnum getEsitoRichiestaPagamento() {
    return esitoRichiestaPagamento;
  }

  public void setEsitoRichiestaPagamento(EsitoRichiestaPagamentoEnum esitoRichiestaPagamento) {
    this.esitoRichiestaPagamento = esitoRichiestaPagamento;
  }

  public InfoPagamentoTelematicoDto flussoRicevuta(String flussoRicevuta) {
    this.flussoRicevuta = flussoRicevuta;
    return this;
  }

   /**
   * Get flussoRicevuta
   * @return flussoRicevuta
  **/
  @ApiModelProperty(value = "")
  public String getFlussoRicevuta() {
    return flussoRicevuta;
  }

  public void setFlussoRicevuta(String flussoRicevuta) {
    this.flussoRicevuta = flussoRicevuta;
  }

  public InfoPagamentoTelematicoDto identificativoDominio(String identificativoDominio) {
    this.identificativoDominio = identificativoDominio;
    return this;
  }

   /**
   * Get identificativoDominio
   * @return identificativoDominio
  **/
  @ApiModelProperty(example = "01556360152", value = "")
  public String getIdentificativoDominio() {
    return identificativoDominio;
  }

  public void setIdentificativoDominio(String identificativoDominio) {
    this.identificativoDominio = identificativoDominio;
  }

  public InfoPagamentoTelematicoDto identificativoUnivocoVersamento(String identificativoUnivocoVersamento) {
    this.identificativoUnivocoVersamento = identificativoUnivocoVersamento;
    return this;
  }

   /**
   * Identificativo Univoco Versamento, attribuito dall&#39;Ente Creditore ad ogni operazione di incasso e che non può essere associato nel tempo ad alcun altro incasso emesso dal medesimo Ente Creditore, max 25 caratteri
   * @return identificativoUnivocoVersamento
  **/
  @ApiModelProperty(example = "04210009695360182", required = true, value = "Identificativo Univoco Versamento, attribuito dall'Ente Creditore ad ogni operazione di incasso e che non può essere associato nel tempo ad alcun altro incasso emesso dal medesimo Ente Creditore, max 25 caratteri")
  public String getIdentificativoUnivocoVersamento() {
    return identificativoUnivocoVersamento;
  }

  public void setIdentificativoUnivocoVersamento(String identificativoUnivocoVersamento) {
    this.identificativoUnivocoVersamento = identificativoUnivocoVersamento;
  }

  public InfoPagamentoTelematicoDto importoTotalePagato(BigDecimal importoTotalePagato) {
    this.importoTotalePagato = importoTotalePagato;
    return this;
  }

   /**
   * Get importoTotalePagato
   * @return importoTotalePagato
  **/
  @ApiModelProperty(example = "0.0", value = "")
  public BigDecimal getImportoTotalePagato() {
    return importoTotalePagato;
  }

  public void setImportoTotalePagato(BigDecimal importoTotalePagato) {
    this.importoTotalePagato = importoTotalePagato;
  }

  public InfoPagamentoTelematicoDto importoTotaleRichiesta(BigDecimal importoTotaleRichiesta) {
    this.importoTotaleRichiesta = importoTotaleRichiesta;
    return this;
  }

   /**
   * Get importoTotaleRichiesta
   * @return importoTotaleRichiesta
  **/
  @ApiModelProperty(example = "59.99", value = "")
  public BigDecimal getImportoTotaleRichiesta() {
    return importoTotaleRichiesta;
  }

  public void setImportoTotaleRichiesta(BigDecimal importoTotaleRichiesta) {
    this.importoTotaleRichiesta = importoTotaleRichiesta;
  }

  public InfoPagamentoTelematicoDto infoVersamentoSingolo(List<InfoSingoloPagamentoDto> infoVersamentoSingolo) {
    this.infoVersamentoSingolo = infoVersamentoSingolo;
    return this;
  }

  public InfoPagamentoTelematicoDto addInfoVersamentoSingoloItem(InfoSingoloPagamentoDto infoVersamentoSingoloItem) {
    if (this.infoVersamentoSingolo == null) {
      this.infoVersamentoSingolo = new ArrayList<InfoSingoloPagamentoDto>();
    }
    this.infoVersamentoSingolo.add(infoVersamentoSingoloItem);
    return this;
  }

   /**
   * Get infoVersamentoSingolo
   * @return infoVersamentoSingolo
  **/
  @ApiModelProperty(value = "")
  public List<InfoSingoloPagamentoDto> getInfoVersamentoSingolo() {
    return infoVersamentoSingolo;
  }

  public void setInfoVersamentoSingolo(List<InfoSingoloPagamentoDto> infoVersamentoSingolo) {
    this.infoVersamentoSingolo = infoVersamentoSingolo;
  }

  public InfoPagamentoTelematicoDto numeroAvviso(String numeroAvviso) {
    this.numeroAvviso = numeroAvviso;
    return this;
  }

   /**
   * Numero avviso, max 18 caratteri
   * @return numeroAvviso
  **/
  @ApiModelProperty(example = "004040000002146431", value = "Numero avviso, max 18 caratteri")
  public String getNumeroAvviso() {
    return numeroAvviso;
  }

  public void setNumeroAvviso(String numeroAvviso) {
    this.numeroAvviso = numeroAvviso;
  }

  public InfoPagamentoTelematicoDto numeroVersamentiSingoli(Integer numeroVersamentiSingoli) {
    this.numeroVersamentiSingoli = numeroVersamentiSingoli;
    return this;
  }

   /**
   * Get numeroVersamentiSingoli
   * @return numeroVersamentiSingoli
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getNumeroVersamentiSingoli() {
    return numeroVersamentiSingoli;
  }

  public void setNumeroVersamentiSingoli(Integer numeroVersamentiSingoli) {
    this.numeroVersamentiSingoli = numeroVersamentiSingoli;
  }

  public InfoPagamentoTelematicoDto statoTecnicoPagamento(StatoTecnicoPagamentoEnum statoTecnicoPagamento) {
    this.statoTecnicoPagamento = statoTecnicoPagamento;
    return this;
  }

   /**
   * Get statoTecnicoPagamento
   * @return statoTecnicoPagamento
  **/
  @ApiModelProperty(example = "NOTIFICATO", value = "")
  public StatoTecnicoPagamentoEnum getStatoTecnicoPagamento() {
    return statoTecnicoPagamento;
  }

  public void setStatoTecnicoPagamento(StatoTecnicoPagamentoEnum statoTecnicoPagamento) {
    this.statoTecnicoPagamento = statoTecnicoPagamento;
  }

  public InfoPagamentoTelematicoDto testoOriginaleRicevuta(String testoOriginaleRicevuta) {
    this.testoOriginaleRicevuta = testoOriginaleRicevuta;
    return this;
  }

   /**
   * Get testoOriginaleRicevuta
   * @return testoOriginaleRicevuta
  **/
  @ApiModelProperty(value = "")
  public String getTestoOriginaleRicevuta() {
    return testoOriginaleRicevuta;
  }

  public void setTestoOriginaleRicevuta(String testoOriginaleRicevuta) {
    this.testoOriginaleRicevuta = testoOriginaleRicevuta;
  }

  public InfoPagamentoTelematicoDto tipoVersamento(TipoVersamentoEnum tipoVersamento) {
    this.tipoVersamento = tipoVersamento;
    return this;
  }

   /**
   * Get tipoVersamento
   * @return tipoVersamento
  **/
  @ApiModelProperty(example = "BBT", value = "")
  public TipoVersamentoEnum getTipoVersamento() {
    return tipoVersamento;
  }

  public void setTipoVersamento(TipoVersamentoEnum tipoVersamento) {
    this.tipoVersamento = tipoVersamento;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InfoPagamentoTelematicoDto infoPagamentoTelematicoDto = (InfoPagamentoTelematicoDto) o;
    return Objects.equals(this.codiceContestoPagamento, infoPagamentoTelematicoDto.codiceContestoPagamento) &&
        Objects.equals(this.dataAccredito, infoPagamentoTelematicoDto.dataAccredito) &&
        Objects.equals(this.dataPagamento, infoPagamentoTelematicoDto.dataPagamento) &&
        Objects.equals(this.datiDebitore, infoPagamentoTelematicoDto.datiDebitore) &&
        Objects.equals(this.datiVersante, infoPagamentoTelematicoDto.datiVersante) &&
        Objects.equals(this.esitoRichiestaPagamento, infoPagamentoTelematicoDto.esitoRichiestaPagamento) &&
        Objects.equals(this.flussoRicevuta, infoPagamentoTelematicoDto.flussoRicevuta) &&
        Objects.equals(this.identificativoDominio, infoPagamentoTelematicoDto.identificativoDominio) &&
        Objects.equals(this.identificativoUnivocoVersamento, infoPagamentoTelematicoDto.identificativoUnivocoVersamento) &&
        Objects.equals(this.importoTotalePagato, infoPagamentoTelematicoDto.importoTotalePagato) &&
        Objects.equals(this.importoTotaleRichiesta, infoPagamentoTelematicoDto.importoTotaleRichiesta) &&
        Objects.equals(this.infoVersamentoSingolo, infoPagamentoTelematicoDto.infoVersamentoSingolo) &&
        Objects.equals(this.numeroAvviso, infoPagamentoTelematicoDto.numeroAvviso) &&
        Objects.equals(this.numeroVersamentiSingoli, infoPagamentoTelematicoDto.numeroVersamentiSingoli) &&
        Objects.equals(this.statoTecnicoPagamento, infoPagamentoTelematicoDto.statoTecnicoPagamento) &&
        Objects.equals(this.testoOriginaleRicevuta, infoPagamentoTelematicoDto.testoOriginaleRicevuta) &&
        Objects.equals(this.tipoVersamento, infoPagamentoTelematicoDto.tipoVersamento);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codiceContestoPagamento, dataAccredito, dataPagamento, datiDebitore, datiVersante, esitoRichiestaPagamento, flussoRicevuta, identificativoDominio, identificativoUnivocoVersamento, importoTotalePagato, importoTotaleRichiesta, infoVersamentoSingolo, numeroAvviso, numeroVersamentiSingoli, statoTecnicoPagamento, testoOriginaleRicevuta, tipoVersamento);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InfoPagamentoTelematicoDto {\n");
    
    sb.append("    codiceContestoPagamento: ").append(toIndentedString(codiceContestoPagamento)).append("\n");
    sb.append("    dataAccredito: ").append(toIndentedString(dataAccredito)).append("\n");
    sb.append("    dataPagamento: ").append(toIndentedString(dataPagamento)).append("\n");
    sb.append("    datiDebitore: ").append(toIndentedString(datiDebitore)).append("\n");
    sb.append("    datiVersante: ").append(toIndentedString(datiVersante)).append("\n");
    sb.append("    esitoRichiestaPagamento: ").append(toIndentedString(esitoRichiestaPagamento)).append("\n");
    sb.append("    flussoRicevuta: ").append(toIndentedString(flussoRicevuta)).append("\n");
    sb.append("    identificativoDominio: ").append(toIndentedString(identificativoDominio)).append("\n");
    sb.append("    identificativoUnivocoVersamento: ").append(toIndentedString(identificativoUnivocoVersamento)).append("\n");
    sb.append("    importoTotalePagato: ").append(toIndentedString(importoTotalePagato)).append("\n");
    sb.append("    importoTotaleRichiesta: ").append(toIndentedString(importoTotaleRichiesta)).append("\n");
    sb.append("    infoVersamentoSingolo: ").append(toIndentedString(infoVersamentoSingolo)).append("\n");
    sb.append("    numeroAvviso: ").append(toIndentedString(numeroAvviso)).append("\n");
    sb.append("    numeroVersamentiSingoli: ").append(toIndentedString(numeroVersamentiSingoli)).append("\n");
    sb.append("    statoTecnicoPagamento: ").append(toIndentedString(statoTecnicoPagamento)).append("\n");
    sb.append("    testoOriginaleRicevuta: ").append(toIndentedString(testoOriginaleRicevuta)).append("\n");
    sb.append("    tipoVersamento: ").append(toIndentedString(tipoVersamento)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

