/*
 * API Gateway Pagamenti
 * Set API REST PagoPA
 *
 * OpenAPI spec version: 1.0
 * Contact: pagamenti.produzione@maggioli.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * JppaLoginRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-23T07:57:29.055Z")
public class JppaLoginRequest {
  @SerializedName("idMessaggio")
  private String idMessaggio = null;

  @SerializedName("identificativoEnte")
  private String identificativoEnte = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("username")
  private String username = null;

  public JppaLoginRequest idMessaggio(String idMessaggio) {
    this.idMessaggio = idMessaggio;
    return this;
  }

   /**
   * Get idMessaggio
   * @return idMessaggio
  **/
  @ApiModelProperty(value = "")
  public String getIdMessaggio() {
    return idMessaggio;
  }

  public void setIdMessaggio(String idMessaggio) {
    this.idMessaggio = idMessaggio;
  }

  public JppaLoginRequest identificativoEnte(String identificativoEnte) {
    this.identificativoEnte = identificativoEnte;
    return this;
  }

   /**
   * Get identificativoEnte
   * @return identificativoEnte
  **/
  @ApiModelProperty(value = "")
  public String getIdentificativoEnte() {
    return identificativoEnte;
  }

  public void setIdentificativoEnte(String identificativoEnte) {
    this.identificativoEnte = identificativoEnte;
  }

  public JppaLoginRequest password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @ApiModelProperty(value = "")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public JppaLoginRequest username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @ApiModelProperty(value = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JppaLoginRequest jppaLoginRequest = (JppaLoginRequest) o;
    return Objects.equals(this.idMessaggio, jppaLoginRequest.idMessaggio) &&
        Objects.equals(this.identificativoEnte, jppaLoginRequest.identificativoEnte) &&
        Objects.equals(this.password, jppaLoginRequest.password) &&
        Objects.equals(this.username, jppaLoginRequest.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idMessaggio, identificativoEnte, password, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JppaLoginRequest {\n");
    
    sb.append("    idMessaggio: ").append(toIndentedString(idMessaggio)).append("\n");
    sb.append("    identificativoEnte: ").append(toIndentedString(identificativoEnte)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

