/*
 * API Gateway Pagamenti
 * Set API REST PagoPA
 *
 * OpenAPI spec version: 1.0
 * Contact: pagamenti.produzione@maggioli.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * JppaLoginResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-23T07:57:29.055Z")
public class JppaLoginResponse {
  @SerializedName("descrizioneErrore")
  private String descrizioneErrore = null;

  @SerializedName("esito")
  private String esito = null;

  @SerializedName("token")
  private String token = null;

  public JppaLoginResponse descrizioneErrore(String descrizioneErrore) {
    this.descrizioneErrore = descrizioneErrore;
    return this;
  }

   /**
   * Get descrizioneErrore
   * @return descrizioneErrore
  **/
  @ApiModelProperty(value = "")
  public String getDescrizioneErrore() {
    return descrizioneErrore;
  }

  public void setDescrizioneErrore(String descrizioneErrore) {
    this.descrizioneErrore = descrizioneErrore;
  }

  public JppaLoginResponse esito(String esito) {
    this.esito = esito;
    return this;
  }

   /**
   * Get esito
   * @return esito
  **/
  @ApiModelProperty(value = "")
  public String getEsito() {
    return esito;
  }

  public void setEsito(String esito) {
    this.esito = esito;
  }

  public JppaLoginResponse token(String token) {
    this.token = token;
    return this;
  }

   /**
   * Get token
   * @return token
  **/
  @ApiModelProperty(value = "")
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JppaLoginResponse jppaLoginResponse = (JppaLoginResponse) o;
    return Objects.equals(this.descrizioneErrore, jppaLoginResponse.descrizioneErrore) &&
        Objects.equals(this.esito, jppaLoginResponse.esito) &&
        Objects.equals(this.token, jppaLoginResponse.token);
  }

  @Override
  public int hashCode() {
    return Objects.hash(descrizioneErrore, esito, token);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JppaLoginResponse {\n");
    
    sb.append("    descrizioneErrore: ").append(toIndentedString(descrizioneErrore)).append("\n");
    sb.append("    esito: ").append(toIndentedString(esito)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

