/*
 * API Gateway Pagamenti
 * Set API REST PagoPA
 *
 * OpenAPI spec version: 1.0
 * Contact: pagamenti.produzione@maggioli.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CtChiaveDebito;
import io.swagger.client.model.CtNumeroAvviso;
import java.io.IOException;

/**
 * ListaScartiCaricamentoDebitiPdp
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-23T07:57:29.055Z")
public class ListaScartiCaricamentoDebitiPdp {
  @SerializedName("chiaveDebito")
  private CtChiaveDebito chiaveDebito = null;

  @SerializedName("numeroAvviso")
  private CtNumeroAvviso numeroAvviso = null;

  public ListaScartiCaricamentoDebitiPdp chiaveDebito(CtChiaveDebito chiaveDebito) {
    this.chiaveDebito = chiaveDebito;
    return this;
  }

   /**
   * Get chiaveDebito
   * @return chiaveDebito
  **/
  @ApiModelProperty(value = "")
  public CtChiaveDebito getChiaveDebito() {
    return chiaveDebito;
  }

  public void setChiaveDebito(CtChiaveDebito chiaveDebito) {
    this.chiaveDebito = chiaveDebito;
  }

  public ListaScartiCaricamentoDebitiPdp numeroAvviso(CtNumeroAvviso numeroAvviso) {
    this.numeroAvviso = numeroAvviso;
    return this;
  }

   /**
   * Get numeroAvviso
   * @return numeroAvviso
  **/
  @ApiModelProperty(value = "")
  public CtNumeroAvviso getNumeroAvviso() {
    return numeroAvviso;
  }

  public void setNumeroAvviso(CtNumeroAvviso numeroAvviso) {
    this.numeroAvviso = numeroAvviso;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListaScartiCaricamentoDebitiPdp listaScartiCaricamentoDebitiPdp = (ListaScartiCaricamentoDebitiPdp) o;
    return Objects.equals(this.chiaveDebito, listaScartiCaricamentoDebitiPdp.chiaveDebito) &&
        Objects.equals(this.numeroAvviso, listaScartiCaricamentoDebitiPdp.numeroAvviso);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chiaveDebito, numeroAvviso);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListaScartiCaricamentoDebitiPdp {\n");
    
    sb.append("    chiaveDebito: ").append(toIndentedString(chiaveDebito)).append("\n");
    sb.append("    numeroAvviso: ").append(toIndentedString(numeroAvviso)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

