/*
 * API Gateway Pagamenti
 * Set API REST PagoPA
 *
 * OpenAPI spec version: 1.0
 * Contact: pagamenti.produzione@maggioli.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Tipo complesso che racchiude le info del debito da modificare
 */
@ApiModel(description = "Tipo complesso che racchiude le info del debito da modificare")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-23T07:57:29.055Z")
public class ModificaGruppoDebitiDto {
  @SerializedName("iuv")
  private String iuv = null;

  @SerializedName("nuovoGruppo")
  private String nuovoGruppo = null;

  public ModificaGruppoDebitiDto iuv(String iuv) {
    this.iuv = iuv;
    return this;
  }

   /**
   * Identificativo Univoco Versamento, attribuito dall&#39;Ente Creditore ad ogni operazione di incasso e che non può essere associato nel tempo ad alcun altro incasso emesso dal medesimo Ente Creditore, max 25 caratteri
   * @return iuv
  **/
  @ApiModelProperty(example = "04210009695360182", required = true, value = "Identificativo Univoco Versamento, attribuito dall'Ente Creditore ad ogni operazione di incasso e che non può essere associato nel tempo ad alcun altro incasso emesso dal medesimo Ente Creditore, max 25 caratteri")
  public String getIuv() {
    return iuv;
  }

  public void setIuv(String iuv) {
    this.iuv = iuv;
  }

  public ModificaGruppoDebitiDto nuovoGruppo(String nuovoGruppo) {
    this.nuovoGruppo = nuovoGruppo;
    return this;
  }

   /**
   * Nuovo gruppo da impostare sul debito
   * @return nuovoGruppo
  **/
  @ApiModelProperty(example = "NUOVO_GRUPPO", required = true, value = "Nuovo gruppo da impostare sul debito")
  public String getNuovoGruppo() {
    return nuovoGruppo;
  }

  public void setNuovoGruppo(String nuovoGruppo) {
    this.nuovoGruppo = nuovoGruppo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModificaGruppoDebitiDto modificaGruppoDebitiDto = (ModificaGruppoDebitiDto) o;
    return Objects.equals(this.iuv, modificaGruppoDebitiDto.iuv) &&
        Objects.equals(this.nuovoGruppo, modificaGruppoDebitiDto.nuovoGruppo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(iuv, nuovoGruppo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModificaGruppoDebitiDto {\n");
    
    sb.append("    iuv: ").append(toIndentedString(iuv)).append("\n");
    sb.append("    nuovoGruppo: ").append(toIndentedString(nuovoGruppo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

