/*
 * API Gateway Pagamenti
 * Set API REST PagoPA
 *
 * OpenAPI spec version: 1.0
 * Contact: pagamenti.produzione@maggioli.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InfoMultibeneficiarioDto;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * MultibeneficiarioDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-23T07:57:29.055Z")
public class MultibeneficiarioDto {
  @SerializedName("importoTotale")
  private BigDecimal importoTotale = null;

  @SerializedName("infoMultibeneficiario")
  private List<InfoMultibeneficiarioDto> infoMultibeneficiario = null;

  @SerializedName("multibeneficiario")
  private Boolean multibeneficiario = null;

  public MultibeneficiarioDto importoTotale(BigDecimal importoTotale) {
    this.importoTotale = importoTotale;
    return this;
  }

   /**
   * Get importoTotale
   * @return importoTotale
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getImportoTotale() {
    return importoTotale;
  }

  public void setImportoTotale(BigDecimal importoTotale) {
    this.importoTotale = importoTotale;
  }

  public MultibeneficiarioDto infoMultibeneficiario(List<InfoMultibeneficiarioDto> infoMultibeneficiario) {
    this.infoMultibeneficiario = infoMultibeneficiario;
    return this;
  }

  public MultibeneficiarioDto addInfoMultibeneficiarioItem(InfoMultibeneficiarioDto infoMultibeneficiarioItem) {
    if (this.infoMultibeneficiario == null) {
      this.infoMultibeneficiario = new ArrayList<InfoMultibeneficiarioDto>();
    }
    this.infoMultibeneficiario.add(infoMultibeneficiarioItem);
    return this;
  }

   /**
   * Get infoMultibeneficiario
   * @return infoMultibeneficiario
  **/
  @ApiModelProperty(value = "")
  public List<InfoMultibeneficiarioDto> getInfoMultibeneficiario() {
    return infoMultibeneficiario;
  }

  public void setInfoMultibeneficiario(List<InfoMultibeneficiarioDto> infoMultibeneficiario) {
    this.infoMultibeneficiario = infoMultibeneficiario;
  }

  public MultibeneficiarioDto multibeneficiario(Boolean multibeneficiario) {
    this.multibeneficiario = multibeneficiario;
    return this;
  }

   /**
   * Get multibeneficiario
   * @return multibeneficiario
  **/
  @ApiModelProperty(value = "")
  public Boolean isMultibeneficiario() {
    return multibeneficiario;
  }

  public void setMultibeneficiario(Boolean multibeneficiario) {
    this.multibeneficiario = multibeneficiario;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultibeneficiarioDto multibeneficiarioDto = (MultibeneficiarioDto) o;
    return Objects.equals(this.importoTotale, multibeneficiarioDto.importoTotale) &&
        Objects.equals(this.infoMultibeneficiario, multibeneficiarioDto.infoMultibeneficiario) &&
        Objects.equals(this.multibeneficiario, multibeneficiarioDto.multibeneficiario);
  }

  @Override
  public int hashCode() {
    return Objects.hash(importoTotale, infoMultibeneficiario, multibeneficiario);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultibeneficiarioDto {\n");
    
    sb.append("    importoTotale: ").append(toIndentedString(importoTotale)).append("\n");
    sb.append("    infoMultibeneficiario: ").append(toIndentedString(infoMultibeneficiario)).append("\n");
    sb.append("    multibeneficiario: ").append(toIndentedString(multibeneficiario)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

