/*
 * API Gateway Pagamenti
 * Set API REST PagoPA
 *
 * OpenAPI spec version: 1.0
 * Contact: pagamenti.produzione@maggioli.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * NumeroAvvisoCheckoutDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-23T07:57:29.055Z")
public class NumeroAvvisoCheckoutDto {
  @SerializedName("importo")
  private BigDecimal importo = null;

  @SerializedName("numeroAvviso")
  private String numeroAvviso = null;

  public NumeroAvvisoCheckoutDto importo(BigDecimal importo) {
    this.importo = importo;
    return this;
  }

   /**
   * Importo con due cifre decimali, massimo valore previsto 999999999.99. Nel caso il numero avviso corrisponda ad un dovuto multibeneficiario l&#39;importo dovrà essere la somma totale delle due componenti del dovuto
   * @return importo
  **/
  @ApiModelProperty(example = "59.99", required = true, value = "Importo con due cifre decimali, massimo valore previsto 999999999.99. Nel caso il numero avviso corrisponda ad un dovuto multibeneficiario l'importo dovrà essere la somma totale delle due componenti del dovuto")
  public BigDecimal getImporto() {
    return importo;
  }

  public void setImporto(BigDecimal importo) {
    this.importo = importo;
  }

  public NumeroAvvisoCheckoutDto numeroAvviso(String numeroAvviso) {
    this.numeroAvviso = numeroAvviso;
    return this;
  }

   /**
   * Deve essere compatibile con le regole definite ed ai parametri assegnati da AGID per il tipo di numero avviso associato all’ente, max 18 caratteri
   * @return numeroAvviso
  **/
  @ApiModelProperty(example = "004040000002146431", required = true, value = "Deve essere compatibile con le regole definite ed ai parametri assegnati da AGID per il tipo di numero avviso associato all’ente, max 18 caratteri")
  public String getNumeroAvviso() {
    return numeroAvviso;
  }

  public void setNumeroAvviso(String numeroAvviso) {
    this.numeroAvviso = numeroAvviso;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NumeroAvvisoCheckoutDto numeroAvvisoCheckoutDto = (NumeroAvvisoCheckoutDto) o;
    return Objects.equals(this.importo, numeroAvvisoCheckoutDto.importo) &&
        Objects.equals(this.numeroAvviso, numeroAvvisoCheckoutDto.numeroAvviso);
  }

  @Override
  public int hashCode() {
    return Objects.hash(importo, numeroAvviso);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NumeroAvvisoCheckoutDto {\n");
    
    sb.append("    importo: ").append(toIndentedString(importo)).append("\n");
    sb.append("    numeroAvviso: ").append(toIndentedString(numeroAvviso)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

