/*
 * API Gateway Pagamenti
 * Set API REST PagoPA
 *
 * OpenAPI spec version: 1.0
 * Contact: pagamenti.produzione@maggioli.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DatiDebitoreDto;
import io.swagger.client.model.DatiVersanteDto;
import io.swagger.client.model.DebitoRiconcilaitoDto;
import java.io.IOException;
import java.math.BigDecimal;
import org.threeten.bp.OffsetDateTime;

/**
 * Nodo contenente tutti i pagamenti singoli contenuti all’interno del sospeso
 */
@ApiModel(description = "Nodo contenente tutti i pagamenti singoli contenuti all’interno del sospeso")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-23T07:57:29.055Z")
public class PagamentoSingoloDto {
  @SerializedName("causaleSingoloPagamento")
  private String causaleSingoloPagamento = null;

  /**
   * Gets or Sets codiceContestoPagamento
   */
  @JsonAdapter(CodiceContestoPagamentoEnum.Adapter.class)
  public enum CodiceContestoPagamentoEnum {
    CCP_TMP_PSPPA("CCP_TMP_PSPPA"),
    
    N_A("N/A");

    private String value;

    CodiceContestoPagamentoEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CodiceContestoPagamentoEnum fromValue(String text) {
      for (CodiceContestoPagamentoEnum b : CodiceContestoPagamentoEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<CodiceContestoPagamentoEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CodiceContestoPagamentoEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CodiceContestoPagamentoEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return CodiceContestoPagamentoEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("codiceContestoPagamento")
  private CodiceContestoPagamentoEnum codiceContestoPagamento = null;

  /**
   * Gets or Sets codiceEsitoSingoloPagamento
   */
  @JsonAdapter(CodiceEsitoSingoloPagamentoEnum.Adapter.class)
  public enum CodiceEsitoSingoloPagamentoEnum {
    DECORR_PARZ_TERMINI("DECORR_PARZ_TERMINI"),
    
    DECORR_TERMINI("DECORR_TERMINI"),
    
    PAG_ESEGUITO("PAG_ESEGUITO"),
    
    PAG_NON_ESEGUITO("PAG_NON_ESEGUITO"),
    
    PAG_PARZ_ESEGUITO("PAG_PARZ_ESEGUITO");

    private String value;

    CodiceEsitoSingoloPagamentoEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CodiceEsitoSingoloPagamentoEnum fromValue(String text) {
      for (CodiceEsitoSingoloPagamentoEnum b : CodiceEsitoSingoloPagamentoEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<CodiceEsitoSingoloPagamentoEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CodiceEsitoSingoloPagamentoEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CodiceEsitoSingoloPagamentoEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return CodiceEsitoSingoloPagamentoEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("codiceEsitoSingoloPagamento")
  private CodiceEsitoSingoloPagamentoEnum codiceEsitoSingoloPagamento = null;

  /**
   * Codice che raggruppa tutte le parametrizzazioni semanticamente omogeneo di debiti. Identifica tipicamente un tributo o più in generale un onere che l’utente finale ha maturato nei confronti della pubblica amministrazione, max 1000 caratteri
   */
  @JsonAdapter(CodiceTipoDebitoEnum.Adapter.class)
  public enum CodiceTipoDebitoEnum {
    CASE_POPOLARI_AFFITTO("CASE_POPOLARI_AFFITTO"),
    
    CIMITERI_SERVIZO("CIMITERI_SERVIZO"),
    
    CIMITERI_VOTIVA("CIMITERI_VOTIVA"),
    
    DEMANIO_CANONE("DEMANIO_CANONE"),
    
    ISTRUTTORIA_SPESE("ISTRUTTORIA_SPESE"),
    
    MENSA("MENSA"),
    
    MULTE("MULTE"),
    
    ONERI("ONERI"),
    
    SAD("SAD"),
    
    SALA_COMUNALE("SALA_COMUNALE"),
    
    SCUOLA_MATERNA_ISCRIZIONE("SCUOLA_MATERNA_ISCRIZIONE"),
    
    SCUOLA_NIDO_RETTA("SCUOLA_NIDO_RETTA"),
    
    SCUOLA_PRE_POST_ORARIO("SCUOLA_PRE_POST_ORARIO"),
    
    SERVIZI("SERVIZI"),
    
    SPORT_PALESTRA("SPORT_PALESTRA"),
    
    SPORT_PISTA("SPORT_PISTA"),
    
    SPORT_STRUTTURA("SPORT_STRUTTURA"),
    
    STABILE_AFFITTO("STABILE_AFFITTO"),
    
    SUAP_ONERI("SUAP_ONERI"),
    
    SUE_ONERI("SUE_ONERI"),
    
    VACANZA_CLIMATICA("VACANZA_CLIMATICA"),
    
    VACANZA_ESTIVO("VACANZA_ESTIVO"),
    
    VERBATEL_RILASCIO("VERBATEL_RILASCIO"),
    
    ZTL_RESIDENTE("ZTL_RESIDENTE"),
    
    ZTL_TEMPORANEA("ZTL_TEMPORANEA");

    private String value;

    CodiceTipoDebitoEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CodiceTipoDebitoEnum fromValue(String text) {
      for (CodiceTipoDebitoEnum b : CodiceTipoDebitoEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<CodiceTipoDebitoEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CodiceTipoDebitoEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CodiceTipoDebitoEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return CodiceTipoDebitoEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("codiceTipoDebito")
  private CodiceTipoDebitoEnum codiceTipoDebito = null;

  @SerializedName("dataEsitoSingoloPagamento")
  private OffsetDateTime dataEsitoSingoloPagamento = null;

  @SerializedName("dataOraMessaggioRicevuta")
  private OffsetDateTime dataOraMessaggioRicevuta = null;

  @SerializedName("datiDebitore")
  private DatiDebitoreDto datiDebitore = null;

  @SerializedName("datiVersante")
  private DatiVersanteDto datiVersante = null;

  @SerializedName("debitoRiconciliato")
  private DebitoRiconcilaitoDto debitoRiconciliato = null;

  /**
   * Indica l’esito della riconciliazione del singolo sospeso, dato un sospeso è possibile avere la lista completa degli iuv che lo compongono, una lista parziale (i.e. perché non tutti gli iuv sono presenti in banca dati come nel caso di multi intermediazione) oppure una lista vuota in quanto il sospeso non è presente in banca dati
   */
  @JsonAdapter(EsitoRiconciliazioneEnum.Adapter.class)
  public enum EsitoRiconciliazioneEnum {
    ERR_DEBITO_DATI_NON_CONGRUENTI("ERR_DEBITO_DATI_NON_CONGRUENTI"),
    
    ERR_DEBITO_NON_TROVATO("ERR_DEBITO_NON_TROVATO"),
    
    ERR_RPT_DATI_NON_CONGRUENTI("ERR_RPT_DATI_NON_CONGRUENTI"),
    
    ERR_RPT_NON_TROVATO("ERR_RPT_NON_TROVATO"),
    
    OK_DEBITO_RICONCILIATO("OK_DEBITO_RICONCILIATO"),
    
    WARN_DEBITO_IMPORTO_NON_PAGATO("WARN_DEBITO_IMPORTO_NON_PAGATO"),
    
    WARN_DEBITO_IMPORTO_PAGATO_NON_CONGRUENTE("WARN_DEBITO_IMPORTO_PAGATO_NON_CONGRUENTE");

    private String value;

    EsitoRiconciliazioneEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static EsitoRiconciliazioneEnum fromValue(String text) {
      for (EsitoRiconciliazioneEnum b : EsitoRiconciliazioneEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<EsitoRiconciliazioneEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final EsitoRiconciliazioneEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public EsitoRiconciliazioneEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return EsitoRiconciliazioneEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("esitoRiconciliazione")
  private EsitoRiconciliazioneEnum esitoRiconciliazione = null;

  @SerializedName("identificativoDominio")
  private String identificativoDominio = null;

  @SerializedName("identificativoMessaggioRicevuta")
  private String identificativoMessaggioRicevuta = null;

  @SerializedName("identificativoUnivocoRiscossione")
  private String identificativoUnivocoRiscossione = null;

  @SerializedName("identificativoUnivocoVersamento")
  private String identificativoUnivocoVersamento = null;

  @SerializedName("messaggio")
  private String messaggio = null;

  @SerializedName("singoloImportoPagato")
  private BigDecimal singoloImportoPagato = null;

  public PagamentoSingoloDto causaleSingoloPagamento(String causaleSingoloPagamento) {
    this.causaleSingoloPagamento = causaleSingoloPagamento;
    return this;
  }

   /**
   * Get causaleSingoloPagamento
   * @return causaleSingoloPagamento
  **/
  @ApiModelProperty(example = "Verbale n.2016/2016/43 (Ente E156, tipo V)", value = "")
  public String getCausaleSingoloPagamento() {
    return causaleSingoloPagamento;
  }

  public void setCausaleSingoloPagamento(String causaleSingoloPagamento) {
    this.causaleSingoloPagamento = causaleSingoloPagamento;
  }

  public PagamentoSingoloDto codiceContestoPagamento(CodiceContestoPagamentoEnum codiceContestoPagamento) {
    this.codiceContestoPagamento = codiceContestoPagamento;
    return this;
  }

   /**
   * Get codiceContestoPagamento
   * @return codiceContestoPagamento
  **/
  @ApiModelProperty(example = "N/A", value = "")
  public CodiceContestoPagamentoEnum getCodiceContestoPagamento() {
    return codiceContestoPagamento;
  }

  public void setCodiceContestoPagamento(CodiceContestoPagamentoEnum codiceContestoPagamento) {
    this.codiceContestoPagamento = codiceContestoPagamento;
  }

  public PagamentoSingoloDto codiceEsitoSingoloPagamento(CodiceEsitoSingoloPagamentoEnum codiceEsitoSingoloPagamento) {
    this.codiceEsitoSingoloPagamento = codiceEsitoSingoloPagamento;
    return this;
  }

   /**
   * Get codiceEsitoSingoloPagamento
   * @return codiceEsitoSingoloPagamento
  **/
  @ApiModelProperty(example = "0", value = "")
  public CodiceEsitoSingoloPagamentoEnum getCodiceEsitoSingoloPagamento() {
    return codiceEsitoSingoloPagamento;
  }

  public void setCodiceEsitoSingoloPagamento(CodiceEsitoSingoloPagamentoEnum codiceEsitoSingoloPagamento) {
    this.codiceEsitoSingoloPagamento = codiceEsitoSingoloPagamento;
  }

  public PagamentoSingoloDto codiceTipoDebito(CodiceTipoDebitoEnum codiceTipoDebito) {
    this.codiceTipoDebito = codiceTipoDebito;
    return this;
  }

   /**
   * Codice che raggruppa tutte le parametrizzazioni semanticamente omogeneo di debiti. Identifica tipicamente un tributo o più in generale un onere che l’utente finale ha maturato nei confronti della pubblica amministrazione, max 1000 caratteri
   * @return codiceTipoDebito
  **/
  @ApiModelProperty(example = "MULTE", required = true, value = "Codice che raggruppa tutte le parametrizzazioni semanticamente omogeneo di debiti. Identifica tipicamente un tributo o più in generale un onere che l’utente finale ha maturato nei confronti della pubblica amministrazione, max 1000 caratteri")
  public CodiceTipoDebitoEnum getCodiceTipoDebito() {
    return codiceTipoDebito;
  }

  public void setCodiceTipoDebito(CodiceTipoDebitoEnum codiceTipoDebito) {
    this.codiceTipoDebito = codiceTipoDebito;
  }

  public PagamentoSingoloDto dataEsitoSingoloPagamento(OffsetDateTime dataEsitoSingoloPagamento) {
    this.dataEsitoSingoloPagamento = dataEsitoSingoloPagamento;
    return this;
  }

   /**
   * Get dataEsitoSingoloPagamento
   * @return dataEsitoSingoloPagamento
  **/
  @ApiModelProperty(example = "1473890400000", value = "")
  public OffsetDateTime getDataEsitoSingoloPagamento() {
    return dataEsitoSingoloPagamento;
  }

  public void setDataEsitoSingoloPagamento(OffsetDateTime dataEsitoSingoloPagamento) {
    this.dataEsitoSingoloPagamento = dataEsitoSingoloPagamento;
  }

  public PagamentoSingoloDto dataOraMessaggioRicevuta(OffsetDateTime dataOraMessaggioRicevuta) {
    this.dataOraMessaggioRicevuta = dataOraMessaggioRicevuta;
    return this;
  }

   /**
   * Get dataOraMessaggioRicevuta
   * @return dataOraMessaggioRicevuta
  **/
  @ApiModelProperty(example = "1473942819000", value = "")
  public OffsetDateTime getDataOraMessaggioRicevuta() {
    return dataOraMessaggioRicevuta;
  }

  public void setDataOraMessaggioRicevuta(OffsetDateTime dataOraMessaggioRicevuta) {
    this.dataOraMessaggioRicevuta = dataOraMessaggioRicevuta;
  }

  public PagamentoSingoloDto datiDebitore(DatiDebitoreDto datiDebitore) {
    this.datiDebitore = datiDebitore;
    return this;
  }

   /**
   * Get datiDebitore
   * @return datiDebitore
  **/
  @ApiModelProperty(value = "")
  public DatiDebitoreDto getDatiDebitore() {
    return datiDebitore;
  }

  public void setDatiDebitore(DatiDebitoreDto datiDebitore) {
    this.datiDebitore = datiDebitore;
  }

  public PagamentoSingoloDto datiVersante(DatiVersanteDto datiVersante) {
    this.datiVersante = datiVersante;
    return this;
  }

   /**
   * Get datiVersante
   * @return datiVersante
  **/
  @ApiModelProperty(value = "")
  public DatiVersanteDto getDatiVersante() {
    return datiVersante;
  }

  public void setDatiVersante(DatiVersanteDto datiVersante) {
    this.datiVersante = datiVersante;
  }

  public PagamentoSingoloDto debitoRiconciliato(DebitoRiconcilaitoDto debitoRiconciliato) {
    this.debitoRiconciliato = debitoRiconciliato;
    return this;
  }

   /**
   * Get debitoRiconciliato
   * @return debitoRiconciliato
  **/
  @ApiModelProperty(value = "")
  public DebitoRiconcilaitoDto getDebitoRiconciliato() {
    return debitoRiconciliato;
  }

  public void setDebitoRiconciliato(DebitoRiconcilaitoDto debitoRiconciliato) {
    this.debitoRiconciliato = debitoRiconciliato;
  }

  public PagamentoSingoloDto esitoRiconciliazione(EsitoRiconciliazioneEnum esitoRiconciliazione) {
    this.esitoRiconciliazione = esitoRiconciliazione;
    return this;
  }

   /**
   * Indica l’esito della riconciliazione del singolo sospeso, dato un sospeso è possibile avere la lista completa degli iuv che lo compongono, una lista parziale (i.e. perché non tutti gli iuv sono presenti in banca dati come nel caso di multi intermediazione) oppure una lista vuota in quanto il sospeso non è presente in banca dati
   * @return esitoRiconciliazione
  **/
  @ApiModelProperty(example = "OK_DEBITO_RICONCILIATO", required = true, value = "Indica l’esito della riconciliazione del singolo sospeso, dato un sospeso è possibile avere la lista completa degli iuv che lo compongono, una lista parziale (i.e. perché non tutti gli iuv sono presenti in banca dati come nel caso di multi intermediazione) oppure una lista vuota in quanto il sospeso non è presente in banca dati")
  public EsitoRiconciliazioneEnum getEsitoRiconciliazione() {
    return esitoRiconciliazione;
  }

  public void setEsitoRiconciliazione(EsitoRiconciliazioneEnum esitoRiconciliazione) {
    this.esitoRiconciliazione = esitoRiconciliazione;
  }

  public PagamentoSingoloDto identificativoDominio(String identificativoDominio) {
    this.identificativoDominio = identificativoDominio;
    return this;
  }

   /**
   * Get identificativoDominio
   * @return identificativoDominio
  **/
  @ApiModelProperty(value = "")
  public String getIdentificativoDominio() {
    return identificativoDominio;
  }

  public void setIdentificativoDominio(String identificativoDominio) {
    this.identificativoDominio = identificativoDominio;
  }

  public PagamentoSingoloDto identificativoMessaggioRicevuta(String identificativoMessaggioRicevuta) {
    this.identificativoMessaggioRicevuta = identificativoMessaggioRicevuta;
    return this;
  }

   /**
   * Get identificativoMessaggioRicevuta
   * @return identificativoMessaggioRicevuta
  **/
  @ApiModelProperty(value = "")
  public String getIdentificativoMessaggioRicevuta() {
    return identificativoMessaggioRicevuta;
  }

  public void setIdentificativoMessaggioRicevuta(String identificativoMessaggioRicevuta) {
    this.identificativoMessaggioRicevuta = identificativoMessaggioRicevuta;
  }

  public PagamentoSingoloDto identificativoUnivocoRiscossione(String identificativoUnivocoRiscossione) {
    this.identificativoUnivocoRiscossione = identificativoUnivocoRiscossione;
    return this;
  }

   /**
   * Get identificativoUnivocoRiscossione
   * @return identificativoUnivocoRiscossione
  **/
  @ApiModelProperty(example = "0000000268919", value = "")
  public String getIdentificativoUnivocoRiscossione() {
    return identificativoUnivocoRiscossione;
  }

  public void setIdentificativoUnivocoRiscossione(String identificativoUnivocoRiscossione) {
    this.identificativoUnivocoRiscossione = identificativoUnivocoRiscossione;
  }

  public PagamentoSingoloDto identificativoUnivocoVersamento(String identificativoUnivocoVersamento) {
    this.identificativoUnivocoVersamento = identificativoUnivocoVersamento;
    return this;
  }

   /**
   * Get identificativoUnivocoVersamento
   * @return identificativoUnivocoVersamento
  **/
  @ApiModelProperty(example = "RF60000000000000000001223", value = "")
  public String getIdentificativoUnivocoVersamento() {
    return identificativoUnivocoVersamento;
  }

  public void setIdentificativoUnivocoVersamento(String identificativoUnivocoVersamento) {
    this.identificativoUnivocoVersamento = identificativoUnivocoVersamento;
  }

  public PagamentoSingoloDto messaggio(String messaggio) {
    this.messaggio = messaggio;
    return this;
  }

   /**
   * Get messaggio
   * @return messaggio
  **/
  @ApiModelProperty(value = "")
  public String getMessaggio() {
    return messaggio;
  }

  public void setMessaggio(String messaggio) {
    this.messaggio = messaggio;
  }

  public PagamentoSingoloDto singoloImportoPagato(BigDecimal singoloImportoPagato) {
    this.singoloImportoPagato = singoloImportoPagato;
    return this;
  }

   /**
   * Get singoloImportoPagato
   * @return singoloImportoPagato
  **/
  @ApiModelProperty(example = "59.99", value = "")
  public BigDecimal getSingoloImportoPagato() {
    return singoloImportoPagato;
  }

  public void setSingoloImportoPagato(BigDecimal singoloImportoPagato) {
    this.singoloImportoPagato = singoloImportoPagato;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PagamentoSingoloDto pagamentoSingoloDto = (PagamentoSingoloDto) o;
    return Objects.equals(this.causaleSingoloPagamento, pagamentoSingoloDto.causaleSingoloPagamento) &&
        Objects.equals(this.codiceContestoPagamento, pagamentoSingoloDto.codiceContestoPagamento) &&
        Objects.equals(this.codiceEsitoSingoloPagamento, pagamentoSingoloDto.codiceEsitoSingoloPagamento) &&
        Objects.equals(this.codiceTipoDebito, pagamentoSingoloDto.codiceTipoDebito) &&
        Objects.equals(this.dataEsitoSingoloPagamento, pagamentoSingoloDto.dataEsitoSingoloPagamento) &&
        Objects.equals(this.dataOraMessaggioRicevuta, pagamentoSingoloDto.dataOraMessaggioRicevuta) &&
        Objects.equals(this.datiDebitore, pagamentoSingoloDto.datiDebitore) &&
        Objects.equals(this.datiVersante, pagamentoSingoloDto.datiVersante) &&
        Objects.equals(this.debitoRiconciliato, pagamentoSingoloDto.debitoRiconciliato) &&
        Objects.equals(this.esitoRiconciliazione, pagamentoSingoloDto.esitoRiconciliazione) &&
        Objects.equals(this.identificativoDominio, pagamentoSingoloDto.identificativoDominio) &&
        Objects.equals(this.identificativoMessaggioRicevuta, pagamentoSingoloDto.identificativoMessaggioRicevuta) &&
        Objects.equals(this.identificativoUnivocoRiscossione, pagamentoSingoloDto.identificativoUnivocoRiscossione) &&
        Objects.equals(this.identificativoUnivocoVersamento, pagamentoSingoloDto.identificativoUnivocoVersamento) &&
        Objects.equals(this.messaggio, pagamentoSingoloDto.messaggio) &&
        Objects.equals(this.singoloImportoPagato, pagamentoSingoloDto.singoloImportoPagato);
  }

  @Override
  public int hashCode() {
    return Objects.hash(causaleSingoloPagamento, codiceContestoPagamento, codiceEsitoSingoloPagamento, codiceTipoDebito, dataEsitoSingoloPagamento, dataOraMessaggioRicevuta, datiDebitore, datiVersante, debitoRiconciliato, esitoRiconciliazione, identificativoDominio, identificativoMessaggioRicevuta, identificativoUnivocoRiscossione, identificativoUnivocoVersamento, messaggio, singoloImportoPagato);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PagamentoSingoloDto {\n");
    
    sb.append("    causaleSingoloPagamento: ").append(toIndentedString(causaleSingoloPagamento)).append("\n");
    sb.append("    codiceContestoPagamento: ").append(toIndentedString(codiceContestoPagamento)).append("\n");
    sb.append("    codiceEsitoSingoloPagamento: ").append(toIndentedString(codiceEsitoSingoloPagamento)).append("\n");
    sb.append("    codiceTipoDebito: ").append(toIndentedString(codiceTipoDebito)).append("\n");
    sb.append("    dataEsitoSingoloPagamento: ").append(toIndentedString(dataEsitoSingoloPagamento)).append("\n");
    sb.append("    dataOraMessaggioRicevuta: ").append(toIndentedString(dataOraMessaggioRicevuta)).append("\n");
    sb.append("    datiDebitore: ").append(toIndentedString(datiDebitore)).append("\n");
    sb.append("    datiVersante: ").append(toIndentedString(datiVersante)).append("\n");
    sb.append("    debitoRiconciliato: ").append(toIndentedString(debitoRiconciliato)).append("\n");
    sb.append("    esitoRiconciliazione: ").append(toIndentedString(esitoRiconciliazione)).append("\n");
    sb.append("    identificativoDominio: ").append(toIndentedString(identificativoDominio)).append("\n");
    sb.append("    identificativoMessaggioRicevuta: ").append(toIndentedString(identificativoMessaggioRicevuta)).append("\n");
    sb.append("    identificativoUnivocoRiscossione: ").append(toIndentedString(identificativoUnivocoRiscossione)).append("\n");
    sb.append("    identificativoUnivocoVersamento: ").append(toIndentedString(identificativoUnivocoVersamento)).append("\n");
    sb.append("    messaggio: ").append(toIndentedString(messaggio)).append("\n");
    sb.append("    singoloImportoPagato: ").append(toIndentedString(singoloImportoPagato)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

