/*
 * API Gateway Pagamenti
 * Set API REST PagoPA
 *
 * OpenAPI spec version: 1.0
 * Contact: pagamenti.produzione@maggioli.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.IdentificativoSospesoDto;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * RichiestaInfoRiconciliazioneDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-23T07:57:29.055Z")
public class RichiestaInfoRiconciliazioneDto {
  @SerializedName("codiceIpaBeneficiario")
  private String codiceIpaBeneficiario = null;

  @SerializedName("listaIdentificativoFlusso")
  private List<String> listaIdentificativoFlusso = null;

  @SerializedName("listaSospesi")
  private List<IdentificativoSospesoDto> listaSospesi = null;

  /**
   * Gets or Sets operazione
   */
  @JsonAdapter(OperazioneEnum.Adapter.class)
  public enum OperazioneEnum {
    IDENTIFICATIVO_FLUSSO("PER_IDENTIFICATIVO_FLUSSO"),
    
    SOSPESI("PER_SOSPESI");

    private String value;

    OperazioneEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static OperazioneEnum fromValue(String text) {
      for (OperazioneEnum b : OperazioneEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<OperazioneEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final OperazioneEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public OperazioneEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return OperazioneEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("operazione")
  private OperazioneEnum operazione = null;

  public RichiestaInfoRiconciliazioneDto codiceIpaBeneficiario(String codiceIpaBeneficiario) {
    this.codiceIpaBeneficiario = codiceIpaBeneficiario;
    return this;
  }

   /**
   * Codice IPA identificativo dell&#39;ente beneficiario
   * @return codiceIpaBeneficiario
  **/
  @ApiModelProperty(example = "EntTest1", required = true, value = "Codice IPA identificativo dell'ente beneficiario")
  public String getCodiceIpaBeneficiario() {
    return codiceIpaBeneficiario;
  }

  public void setCodiceIpaBeneficiario(String codiceIpaBeneficiario) {
    this.codiceIpaBeneficiario = codiceIpaBeneficiario;
  }

  public RichiestaInfoRiconciliazioneDto listaIdentificativoFlusso(List<String> listaIdentificativoFlusso) {
    this.listaIdentificativoFlusso = listaIdentificativoFlusso;
    return this;
  }

  public RichiestaInfoRiconciliazioneDto addListaIdentificativoFlussoItem(String listaIdentificativoFlussoItem) {
    if (this.listaIdentificativoFlusso == null) {
      this.listaIdentificativoFlusso = new ArrayList<String>();
    }
    this.listaIdentificativoFlusso.add(listaIdentificativoFlussoItem);
    return this;
  }

   /**
   * Get listaIdentificativoFlusso
   * @return listaIdentificativoFlusso
  **/
  @ApiModelProperty(example = "\"2016-10-06CIPBITMM-15-31-47-70580\"", value = "")
  public List<String> getListaIdentificativoFlusso() {
    return listaIdentificativoFlusso;
  }

  public void setListaIdentificativoFlusso(List<String> listaIdentificativoFlusso) {
    this.listaIdentificativoFlusso = listaIdentificativoFlusso;
  }

  public RichiestaInfoRiconciliazioneDto listaSospesi(List<IdentificativoSospesoDto> listaSospesi) {
    this.listaSospesi = listaSospesi;
    return this;
  }

  public RichiestaInfoRiconciliazioneDto addListaSospesiItem(IdentificativoSospesoDto listaSospesiItem) {
    if (this.listaSospesi == null) {
      this.listaSospesi = new ArrayList<IdentificativoSospesoDto>();
    }
    this.listaSospesi.add(listaSospesiItem);
    return this;
  }

   /**
   * Get listaSospesi
   * @return listaSospesi
  **/
  @ApiModelProperty(value = "")
  public List<IdentificativoSospesoDto> getListaSospesi() {
    return listaSospesi;
  }

  public void setListaSospesi(List<IdentificativoSospesoDto> listaSospesi) {
    this.listaSospesi = listaSospesi;
  }

  public RichiestaInfoRiconciliazioneDto operazione(OperazioneEnum operazione) {
    this.operazione = operazione;
    return this;
  }

   /**
   * Get operazione
   * @return operazione
  **/
  @ApiModelProperty(value = "")
  public OperazioneEnum getOperazione() {
    return operazione;
  }

  public void setOperazione(OperazioneEnum operazione) {
    this.operazione = operazione;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RichiestaInfoRiconciliazioneDto richiestaInfoRiconciliazioneDto = (RichiestaInfoRiconciliazioneDto) o;
    return Objects.equals(this.codiceIpaBeneficiario, richiestaInfoRiconciliazioneDto.codiceIpaBeneficiario) &&
        Objects.equals(this.listaIdentificativoFlusso, richiestaInfoRiconciliazioneDto.listaIdentificativoFlusso) &&
        Objects.equals(this.listaSospesi, richiestaInfoRiconciliazioneDto.listaSospesi) &&
        Objects.equals(this.operazione, richiestaInfoRiconciliazioneDto.operazione);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codiceIpaBeneficiario, listaIdentificativoFlusso, listaSospesi, operazione);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RichiestaInfoRiconciliazioneDto {\n");
    
    sb.append("    codiceIpaBeneficiario: ").append(toIndentedString(codiceIpaBeneficiario)).append("\n");
    sb.append("    listaIdentificativoFlusso: ").append(toIndentedString(listaIdentificativoFlusso)).append("\n");
    sb.append("    listaSospesi: ").append(toIndentedString(listaSospesi)).append("\n");
    sb.append("    operazione: ").append(toIndentedString(operazione)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

