/*
 * API Gateway Pagamenti
 * Set API REST PagoPA
 *
 * OpenAPI spec version: 1.0
 * Contact: pagamenti.produzione@maggioli.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DovutoDto;
import java.io.IOException;

/**
 * RichiestaInviaDovutoRestDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-23T07:57:29.055Z")
public class RichiestaInviaDovutoRestDto {
  @SerializedName("codiceIPA")
  private String codiceIPA = null;

  @SerializedName("codiceServizio")
  private String codiceServizio = null;

  @SerializedName("dovuto")
  private DovutoDto dovuto = null;

  @SerializedName("transactional")
  private Boolean transactional = null;

  public RichiestaInviaDovutoRestDto codiceIPA(String codiceIPA) {
    this.codiceIPA = codiceIPA;
    return this;
  }

   /**
   * Codice IPA identificativo dell’ente
   * @return codiceIPA
  **/
  @ApiModelProperty(example = "EntTest1", value = "Codice IPA identificativo dell’ente")
  public String getCodiceIPA() {
    return codiceIPA;
  }

  public void setCodiceIPA(String codiceIPA) {
    this.codiceIPA = codiceIPA;
  }

  public RichiestaInviaDovutoRestDto codiceServizio(String codiceServizio) {
    this.codiceServizio = codiceServizio;
    return this;
  }

   /**
   * Codice del servizio chiamante
   * @return codiceServizio
  **/
  @ApiModelProperty(example = "JTRIB", value = "Codice del servizio chiamante")
  public String getCodiceServizio() {
    return codiceServizio;
  }

  public void setCodiceServizio(String codiceServizio) {
    this.codiceServizio = codiceServizio;
  }

  public RichiestaInviaDovutoRestDto dovuto(DovutoDto dovuto) {
    this.dovuto = dovuto;
    return this;
  }

   /**
   * Get dovuto
   * @return dovuto
  **/
  @ApiModelProperty(value = "")
  public DovutoDto getDovuto() {
    return dovuto;
  }

  public void setDovuto(DovutoDto dovuto) {
    this.dovuto = dovuto;
  }

  public RichiestaInviaDovutoRestDto transactional(Boolean transactional) {
    this.transactional = transactional;
    return this;
  }

   /**
   * Flag per far sì che la transazione sia unica o meno
   * @return transactional
  **/
  @ApiModelProperty(example = "false", value = "Flag per far sì che la transazione sia unica o meno")
  public Boolean isTransactional() {
    return transactional;
  }

  public void setTransactional(Boolean transactional) {
    this.transactional = transactional;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RichiestaInviaDovutoRestDto richiestaInviaDovutoRestDto = (RichiestaInviaDovutoRestDto) o;
    return Objects.equals(this.codiceIPA, richiestaInviaDovutoRestDto.codiceIPA) &&
        Objects.equals(this.codiceServizio, richiestaInviaDovutoRestDto.codiceServizio) &&
        Objects.equals(this.dovuto, richiestaInviaDovutoRestDto.dovuto) &&
        Objects.equals(this.transactional, richiestaInviaDovutoRestDto.transactional);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codiceIPA, codiceServizio, dovuto, transactional);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RichiestaInviaDovutoRestDto {\n");
    
    sb.append("    codiceIPA: ").append(toIndentedString(codiceIPA)).append("\n");
    sb.append("    codiceServizio: ").append(toIndentedString(codiceServizio)).append("\n");
    sb.append("    dovuto: ").append(toIndentedString(dovuto)).append("\n");
    sb.append("    transactional: ").append(toIndentedString(transactional)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

