/*
 * API Gateway Pagamenti
 * Set API REST PagoPA
 *
 * OpenAPI spec version: 1.0
 * Contact: pagamenti.produzione@maggioli.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.IdentificativoSospesoDto;
import io.swagger.client.model.PagamentoSingoloDto;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * Nodo che contiene i dettagli del singolo sospeso riconciliato
 */
@ApiModel(description = "Nodo che contiene i dettagli del singolo sospeso riconciliato")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-23T07:57:29.055Z")
public class SospesoRiconciliatoDto {
  @SerializedName("codiceBicBancaDiRiversamento")
  private String codiceBicBancaDiRiversamento = null;

  @SerializedName("codiceIdentificativoUnivocoMittente")
  private String codiceIdentificativoUnivocoMittente = null;

  @SerializedName("dataOraFlusso")
  private OffsetDateTime dataOraFlusso = null;

  @SerializedName("dataRegolamento")
  private OffsetDateTime dataRegolamento = null;

  @SerializedName("identificativoFlusso")
  private String identificativoFlusso = null;

  @SerializedName("identificativoSospeso")
  private IdentificativoSospesoDto identificativoSospeso = null;

  @SerializedName("identificativoUnivocoRegolamento")
  private String identificativoUnivocoRegolamento = null;

  @SerializedName("importoTotalePagamentiRendicontati")
  private BigDecimal importoTotalePagamentiRendicontati = null;

  @SerializedName("numeroTotalePagamentiRendicontati")
  private Integer numeroTotalePagamentiRendicontati = null;

  @SerializedName("pagamentiSingoli")
  private List<PagamentoSingoloDto> pagamentiSingoli = new ArrayList<PagamentoSingoloDto>();

  /**
   * Tipologia del PSP che ha effettuato il riversamento
   */
  @JsonAdapter(TipoIdentificativoUnivocoMittenteEnum.Adapter.class)
  public enum TipoIdentificativoUnivocoMittenteEnum {
    A_CODICE_ABI("A = codice ABI"),
    
    B_CODICE_BIC("B = codice BIC"),
    
    G_PERSONA_GIURIDICA("G = persona giuridica");

    private String value;

    TipoIdentificativoUnivocoMittenteEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TipoIdentificativoUnivocoMittenteEnum fromValue(String text) {
      for (TipoIdentificativoUnivocoMittenteEnum b : TipoIdentificativoUnivocoMittenteEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<TipoIdentificativoUnivocoMittenteEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TipoIdentificativoUnivocoMittenteEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TipoIdentificativoUnivocoMittenteEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return TipoIdentificativoUnivocoMittenteEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("tipoIdentificativoUnivocoMittente")
  private TipoIdentificativoUnivocoMittenteEnum tipoIdentificativoUnivocoMittente = null;

  public SospesoRiconciliatoDto codiceBicBancaDiRiversamento(String codiceBicBancaDiRiversamento) {
    this.codiceBicBancaDiRiversamento = codiceBicBancaDiRiversamento;
    return this;
  }

   /**
   * Codice BIC del PSP che ha effettuato il riversamento
   * @return codiceBicBancaDiRiversamento
  **/
  @ApiModelProperty(example = "CIPBITMM", value = "Codice BIC del PSP che ha effettuato il riversamento")
  public String getCodiceBicBancaDiRiversamento() {
    return codiceBicBancaDiRiversamento;
  }

  public void setCodiceBicBancaDiRiversamento(String codiceBicBancaDiRiversamento) {
    this.codiceBicBancaDiRiversamento = codiceBicBancaDiRiversamento;
  }

  public SospesoRiconciliatoDto codiceIdentificativoUnivocoMittente(String codiceIdentificativoUnivocoMittente) {
    this.codiceIdentificativoUnivocoMittente = codiceIdentificativoUnivocoMittente;
    return this;
  }

   /**
   * Codice del PSP che ha effettuato il riversamento, può essere il codice fiscale o la partita IVA
   * @return codiceIdentificativoUnivocoMittente
  **/
  @ApiModelProperty(example = "05000", value = "Codice del PSP che ha effettuato il riversamento, può essere il codice fiscale o la partita IVA")
  public String getCodiceIdentificativoUnivocoMittente() {
    return codiceIdentificativoUnivocoMittente;
  }

  public void setCodiceIdentificativoUnivocoMittente(String codiceIdentificativoUnivocoMittente) {
    this.codiceIdentificativoUnivocoMittente = codiceIdentificativoUnivocoMittente;
  }

  public SospesoRiconciliatoDto dataOraFlusso(OffsetDateTime dataOraFlusso) {
    this.dataOraFlusso = dataOraFlusso;
    return this;
  }

   /**
   * Indica la data e ora di creazione del flusso
   * @return dataOraFlusso
  **/
  @ApiModelProperty(example = "1475760707000", value = "Indica la data e ora di creazione del flusso")
  public OffsetDateTime getDataOraFlusso() {
    return dataOraFlusso;
  }

  public void setDataOraFlusso(OffsetDateTime dataOraFlusso) {
    this.dataOraFlusso = dataOraFlusso;
  }

  public SospesoRiconciliatoDto dataRegolamento(OffsetDateTime dataRegolamento) {
    this.dataRegolamento = dataRegolamento;
    return this;
  }

   /**
   * Indica la data di esecuzione dell’operazione di trasferimento fondi con la quale viene regolato contabilmente il riversamento delle somme incassate
   * @return dataRegolamento
  **/
  @ApiModelProperty(example = "1475704800000", value = "Indica la data di esecuzione dell’operazione di trasferimento fondi con la quale viene regolato contabilmente il riversamento delle somme incassate")
  public OffsetDateTime getDataRegolamento() {
    return dataRegolamento;
  }

  public void setDataRegolamento(OffsetDateTime dataRegolamento) {
    this.dataRegolamento = dataRegolamento;
  }

  public SospesoRiconciliatoDto identificativoFlusso(String identificativoFlusso) {
    this.identificativoFlusso = identificativoFlusso;
    return this;
  }

   /**
   * Identificativo legato alla generazione e trasmissione del flusso di riversamento. Deve essere univoco nell’ambito dell’anno di riferimento delle operazioni di pagamento cui si riferisce il flusso
   * @return identificativoFlusso
  **/
  @ApiModelProperty(example = "2016-10-06CIPBITMM-15-31-47-70580", value = "Identificativo legato alla generazione e trasmissione del flusso di riversamento. Deve essere univoco nell’ambito dell’anno di riferimento delle operazioni di pagamento cui si riferisce il flusso")
  public String getIdentificativoFlusso() {
    return identificativoFlusso;
  }

  public void setIdentificativoFlusso(String identificativoFlusso) {
    this.identificativoFlusso = identificativoFlusso;
  }

  public SospesoRiconciliatoDto identificativoSospeso(IdentificativoSospesoDto identificativoSospeso) {
    this.identificativoSospeso = identificativoSospeso;
    return this;
  }

   /**
   * Get identificativoSospeso
   * @return identificativoSospeso
  **/
  @ApiModelProperty(value = "")
  public IdentificativoSospesoDto getIdentificativoSospeso() {
    return identificativoSospeso;
  }

  public void setIdentificativoSospeso(IdentificativoSospesoDto identificativoSospeso) {
    this.identificativoSospeso = identificativoSospeso;
  }

  public SospesoRiconciliatoDto identificativoUnivocoRegolamento(String identificativoUnivocoRegolamento) {
    this.identificativoUnivocoRegolamento = identificativoUnivocoRegolamento;
    return this;
  }

   /**
   * Riferimento assegnato dal prestatore di servizi di pagamento all’operazione di trasferimento fondi con la quale viene regolato contabilmente il riversamento delle somme incassate ovvero l’accumulo dei bonifici disposti dai clienti (TRN)
   * @return identificativoUnivocoRegolamento
  **/
  @ApiModelProperty(example = "380001142016AGID480160001600IT", value = "Riferimento assegnato dal prestatore di servizi di pagamento all’operazione di trasferimento fondi con la quale viene regolato contabilmente il riversamento delle somme incassate ovvero l’accumulo dei bonifici disposti dai clienti (TRN)")
  public String getIdentificativoUnivocoRegolamento() {
    return identificativoUnivocoRegolamento;
  }

  public void setIdentificativoUnivocoRegolamento(String identificativoUnivocoRegolamento) {
    this.identificativoUnivocoRegolamento = identificativoUnivocoRegolamento;
  }

  public SospesoRiconciliatoDto importoTotalePagamentiRendicontati(BigDecimal importoTotalePagamentiRendicontati) {
    this.importoTotalePagamentiRendicontati = importoTotalePagamentiRendicontati;
    return this;
  }

   /**
   * Get importoTotalePagamentiRendicontati
   * @return importoTotalePagamentiRendicontati
  **/
  @ApiModelProperty(example = "59.99", value = "")
  public BigDecimal getImportoTotalePagamentiRendicontati() {
    return importoTotalePagamentiRendicontati;
  }

  public void setImportoTotalePagamentiRendicontati(BigDecimal importoTotalePagamentiRendicontati) {
    this.importoTotalePagamentiRendicontati = importoTotalePagamentiRendicontati;
  }

  public SospesoRiconciliatoDto numeroTotalePagamentiRendicontati(Integer numeroTotalePagamentiRendicontati) {
    this.numeroTotalePagamentiRendicontati = numeroTotalePagamentiRendicontati;
    return this;
  }

   /**
   * Get numeroTotalePagamentiRendicontati
   * @return numeroTotalePagamentiRendicontati
  **/
  @ApiModelProperty(example = "1", value = "")
  public Integer getNumeroTotalePagamentiRendicontati() {
    return numeroTotalePagamentiRendicontati;
  }

  public void setNumeroTotalePagamentiRendicontati(Integer numeroTotalePagamentiRendicontati) {
    this.numeroTotalePagamentiRendicontati = numeroTotalePagamentiRendicontati;
  }

  public SospesoRiconciliatoDto pagamentiSingoli(List<PagamentoSingoloDto> pagamentiSingoli) {
    this.pagamentiSingoli = pagamentiSingoli;
    return this;
  }

  public SospesoRiconciliatoDto addPagamentiSingoliItem(PagamentoSingoloDto pagamentiSingoliItem) {
    this.pagamentiSingoli.add(pagamentiSingoliItem);
    return this;
  }

   /**
   * Get pagamentiSingoli
   * @return pagamentiSingoli
  **/
  @ApiModelProperty(required = true, value = "")
  public List<PagamentoSingoloDto> getPagamentiSingoli() {
    return pagamentiSingoli;
  }

  public void setPagamentiSingoli(List<PagamentoSingoloDto> pagamentiSingoli) {
    this.pagamentiSingoli = pagamentiSingoli;
  }

  public SospesoRiconciliatoDto tipoIdentificativoUnivocoMittente(TipoIdentificativoUnivocoMittenteEnum tipoIdentificativoUnivocoMittente) {
    this.tipoIdentificativoUnivocoMittente = tipoIdentificativoUnivocoMittente;
    return this;
  }

   /**
   * Tipologia del PSP che ha effettuato il riversamento
   * @return tipoIdentificativoUnivocoMittente
  **/
  @ApiModelProperty(example = "A", value = "Tipologia del PSP che ha effettuato il riversamento")
  public TipoIdentificativoUnivocoMittenteEnum getTipoIdentificativoUnivocoMittente() {
    return tipoIdentificativoUnivocoMittente;
  }

  public void setTipoIdentificativoUnivocoMittente(TipoIdentificativoUnivocoMittenteEnum tipoIdentificativoUnivocoMittente) {
    this.tipoIdentificativoUnivocoMittente = tipoIdentificativoUnivocoMittente;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SospesoRiconciliatoDto sospesoRiconciliatoDto = (SospesoRiconciliatoDto) o;
    return Objects.equals(this.codiceBicBancaDiRiversamento, sospesoRiconciliatoDto.codiceBicBancaDiRiversamento) &&
        Objects.equals(this.codiceIdentificativoUnivocoMittente, sospesoRiconciliatoDto.codiceIdentificativoUnivocoMittente) &&
        Objects.equals(this.dataOraFlusso, sospesoRiconciliatoDto.dataOraFlusso) &&
        Objects.equals(this.dataRegolamento, sospesoRiconciliatoDto.dataRegolamento) &&
        Objects.equals(this.identificativoFlusso, sospesoRiconciliatoDto.identificativoFlusso) &&
        Objects.equals(this.identificativoSospeso, sospesoRiconciliatoDto.identificativoSospeso) &&
        Objects.equals(this.identificativoUnivocoRegolamento, sospesoRiconciliatoDto.identificativoUnivocoRegolamento) &&
        Objects.equals(this.importoTotalePagamentiRendicontati, sospesoRiconciliatoDto.importoTotalePagamentiRendicontati) &&
        Objects.equals(this.numeroTotalePagamentiRendicontati, sospesoRiconciliatoDto.numeroTotalePagamentiRendicontati) &&
        Objects.equals(this.pagamentiSingoli, sospesoRiconciliatoDto.pagamentiSingoli) &&
        Objects.equals(this.tipoIdentificativoUnivocoMittente, sospesoRiconciliatoDto.tipoIdentificativoUnivocoMittente);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codiceBicBancaDiRiversamento, codiceIdentificativoUnivocoMittente, dataOraFlusso, dataRegolamento, identificativoFlusso, identificativoSospeso, identificativoUnivocoRegolamento, importoTotalePagamentiRendicontati, numeroTotalePagamentiRendicontati, pagamentiSingoli, tipoIdentificativoUnivocoMittente);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SospesoRiconciliatoDto {\n");
    
    sb.append("    codiceBicBancaDiRiversamento: ").append(toIndentedString(codiceBicBancaDiRiversamento)).append("\n");
    sb.append("    codiceIdentificativoUnivocoMittente: ").append(toIndentedString(codiceIdentificativoUnivocoMittente)).append("\n");
    sb.append("    dataOraFlusso: ").append(toIndentedString(dataOraFlusso)).append("\n");
    sb.append("    dataRegolamento: ").append(toIndentedString(dataRegolamento)).append("\n");
    sb.append("    identificativoFlusso: ").append(toIndentedString(identificativoFlusso)).append("\n");
    sb.append("    identificativoSospeso: ").append(toIndentedString(identificativoSospeso)).append("\n");
    sb.append("    identificativoUnivocoRegolamento: ").append(toIndentedString(identificativoUnivocoRegolamento)).append("\n");
    sb.append("    importoTotalePagamentiRendicontati: ").append(toIndentedString(importoTotalePagamentiRendicontati)).append("\n");
    sb.append("    numeroTotalePagamentiRendicontati: ").append(toIndentedString(numeroTotalePagamentiRendicontati)).append("\n");
    sb.append("    pagamentiSingoli: ").append(toIndentedString(pagamentiSingoli)).append("\n");
    sb.append("    tipoIdentificativoUnivocoMittente: ").append(toIndentedString(tipoIdentificativoUnivocoMittente)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

