/*
 * API Gateway Pagamenti
 * Set API REST PagoPA
 *
 * OpenAPI spec version: 1.0
 * Contact: pagamenti.produzione@maggioli.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.EstrattoContoDto;
import io.swagger.client.model.EstrattoContoSearchFilter;
import io.swagger.client.model.StandardAPIErrorResponse;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EstrattoContoApi
 */
@Ignore
public class EstrattoContoApiTest {

    private final EstrattoContoApi api = new EstrattoContoApi();

    
    /**
     * Restituisce i debiti filtrati dai parametri passati in input
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getEstrattoContoUsingPOSTTest() throws Exception {
        EstrattoContoSearchFilter filtriRicercaEstrattoConto = null;
        EstrattoContoDto response = api.getEstrattoContoUsingPOST(filtriRicercaEstrattoConto);

        // TODO: test validations
    }
    
}
